"""Canonical Pydantic case-models — one per organ.

Each ``<Organ>CancerCase`` is the SINGLE SOURCE OF TRUTH for the organ's
extracted fields. DSPy signatures are built dynamically from these
case-models by ``digital_registrar_research.signatures.factory``; JSON
schemas are auto-generated by the ``registrar-schemas`` CLI from
``model_json_schema()``. The registry ``CASE_MODELS`` maps the public
organ key (as used in the ``cancer_category`` Literal and JSON schema
filenames) to its Pydantic class.
"""
from pydantic import BaseModel

from ._common import IsCancerCase, ReportJsonizeOutput
from ._factory_helpers import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    field_desc,
    field_group,
    group_instructions,
    group_order,
    iter_custom_types,
    iter_fields_by_group,
)
from .breast import BreastCancerCase
from .cervix import CervixCancerCase
from .colorectal import ColorectalCancerCase
from .esophagus import EsophagusCancerCase
from .liver import LiverCancerCase
from .lung import LungCancerCase
from .pancreas import PancreasCancerCase
from .prostate import ProstateCancerCase
from .stomach import StomachCancerCase
from .thyroid import ThyroidCancerCase

CASE_MODELS: dict[str, type[BaseModel]] = {
    "breast":     BreastCancerCase,
    "cervix":     CervixCancerCase,
    "colorectal": ColorectalCancerCase,
    "esophagus":  EsophagusCancerCase,
    "liver":      LiverCancerCase,
    "lung":       LungCancerCase,
    "pancreas":   PancreasCancerCase,
    "prostate":   ProstateCancerCase,
    "stomach":    StomachCancerCase,
    "thyroid":    ThyroidCancerCase,
}

__all__ = [
    "CASE_MODELS",
    "IsCancerCase", "ReportJsonizeOutput",
    "BreastCancerCase", "CervixCancerCase", "ColorectalCancerCase",
    "EsophagusCancerCase", "LiverCancerCase", "LungCancerCase",
    "PancreasCancerCase", "ProstateCancerCase", "StomachCancerCase",
    "ThyroidCancerCase",
    # Schema-authoring helpers re-exported for the GUI and the factory.
    "DEFAULT_GROUP_INSTRUCTION",
    "GroupedField",
    "field_desc",
    "field_group",
    "group_instructions",
    "group_order",
    "iter_custom_types",
    "iter_fields_by_group",
]
