"""Canonical case-model for breast cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class (with synthesised
``BreastMargin`` / ``BreastLN`` / ``BreastBiomarker`` types and the full
staging block) is built by the :func:`assemble_case_model` decorator.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    BiomarkerSpec,
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    LymphNodeSide,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class BreastCancerCase(BaseModel):
    """Canonical extracted case record for breast cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given breast cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'dcis': 'You need to extract data about ductal carcinoma in situ below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'grading': 'you need to extract the value of the specified items below from the given breast cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given breast cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given breast cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given breast cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'biomarkers': 'you need to extract breast cancer biomarkers, which is very important, below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['partial_mastectomy', 'simple_mastectomy', 'breast_conserving_surgery', 'modified_radical_mastectomy', 'total_mastectomy', 'wide_excision', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. partial mastectomy")
    cancer_quadrant: Literal['upper_outer_quadrant', 'upper_inner_quadrant', 'lower_outer_quadrant', 'lower_inner_quadrant', 'nipple', 'others']|None = GroupedField(
        group='nonnested',
        desc="identify the primary site of cancer. e.g. upper outer quadrant. please consider what side is the breast excision specimen when you determine the quadrant",
    )
    cancer_clock: Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]|None = GroupedField(group='nonnested', desc="identify the clock position of the cancer if mentioned. e.g. 3")
    cancer_laterality: Literal['right', 'left', 'bilateral']|None = GroupedField(group='nonnested', desc="identify the side of the cancer. e.g. right")
    histology: Literal["invasive_carcinoma_no_special_type", "invasive_lobular_carcinoma", "mixed_ductal_and_lobular_carcinoma", "tubular_adenocarcinoma", "mucinous_adenocarcinoma",  "encapsulated_papillary_carcinoma", "solid_papillary_carcinoma", "inflammatory_carcinoma", "other_special_types"]|None = GroupedField(
        group='nonnested',
        desc="identify the histological type of the cancer. e.g. invasive carcinoma of no special type. If the histological type is not included in the above list, please code as other_special_types and specify the histological type in the description field.",
    )
    tumor_size: int|None = GroupedField(
        group='nonnested',
        desc="identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor",
    )
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- dcis ---
    dcis_present: bool|None = GroupedField(group='dcis', desc="check whether or not ductal carcinoma in situ is present")
    dcis_size: int|None = GroupedField(
        group='dcis',
        desc="if ductal carcinoma in situ is present, identify the size of the largest DCIS in mm, rounded",
    )
    dcis_comedo_necrosis: bool|None = GroupedField(
        group='dcis',
        desc="if ductal carcinoma in situ is present, check whether or not comedo necrosis is present",
    )
    dcis_grade: Literal[1, 2, 3]|None = GroupedField(
        group='dcis',
        desc="if ductal carcinoma in situ is present, identify the grade of DCIS, low grade (grade 1), intermediate grade (grade 2), high grade (grade 3)",
    )

    # --- grading ---
    nuclear_grade: Literal[1, 2, 3]|None = GroupedField(group='grading', desc="identify the nuclear grade of the tumor")
    tubule_formation: Literal[1, 2, 3]|None = GroupedField(group='grading', desc="identify the tubule formation score of the tumor")
    mitotic_rate: Literal[1, 2, 3]|None = GroupedField(group='grading', desc="identify the mitotic rate score of the tumor")
    total_score: Literal[3, 4, 5, 6, 7, 8, 9]|None = GroupedField(group='grading', desc="identify the total score of the tumor")
    grade: Literal[1, 2, 3]|None = GroupedField(group='grading', desc="identify the grade of the tumor")

    # --- staging ---  (generated by StagingSpec.emit_fields())
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "tis", "t1mi", "t1a", "t1b", "t1c", "t2", "t3", "t4a", "t4b", "t4c"],
        pn=Literal["nx", "n0", "n1mi", "n1a", "n1b", "n1c", "n2a", "n2b", "n3a", "n3b", "n3c"],
        stage_groups={
            "pathologic_stage_group": (
                Literal["0", "ia", "ib", "iia", "iib", "iiia", "iiib", "iiic", "iv"],
                "identify the pathologic stage group of the tumor, return none if only anatomical stage group is given, dont guess",
            ),
            "anatomic_stage_group": Literal["0", "ia", "ib", "iia", "iib", "iiia", "iiib", "iiic", "iv"],
        },
    )

    # --- margins ---  (auto-expanded to list[BreastMargin])
    margins: Literal[
        "12_3_clock", "3_6_clock", "6_9_clock", "9_12_clock",
        "12_clock", "3_clock", "6_clock", "9_clock",
        "superficial", "base",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"distal\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"radial\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[BreastLN])
    regional_lymph_node: Literal[
        "sentinel", "nonsentinel", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_side\": \"right\", \"lymph_node_category\": \"sentinel\", \"involved\": 2, \"examined\": 5, \"station_name\": \"station 1\"}, {\"lymph_node_side\": \"left\", \"lymph_node_category\": \"nonsentinel\", \"involved\": 0, \"examined\": 3, \"station_name\": \"station 2\"}, ...]. If not present, just output null for every lymph node",
        side=LymphNodeSide,
        category_desc=(
            "acceptable value for lymph node categories (i.e. stations) in breast cancer. "
            "If not included in these standard lymph node 'station' number, should be "
            "classified as others."
        ),
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )

    # --- biomarkers ---  (auto-expanded to list[BreastBiomarker])
    biomarkers: list = BiomarkerSpec(
        desc="""return all of the examined immunoreceptors using immunohistochemistry techniques,like er, pr, her2, ki67, etc. in a list of pydantic structures,
    example: [{"biomarker_category": "er", "expression": true, "percentage": 90, "score": null, "biomarker_name": "estrogen receptor"},
    {"biomarker_category": "pr", "expression": false, "percentage": 0, "score": null, "biomarker_name": "progesterone receptor"},
    {"biomarker_category": "her2", "expression": null, "percentage": 0, "score": 2, "biomarker_name": "human epidermal growth factor receptor 2"},
    {"biomarker_category": "ki67", "expression": null, "percentage": 30, "score": null, "biomarker_name": "ki67 proliferation index"}]. If not present, just output null for every biomarker""",
        categories=Literal["er", "pr", "her2", "ki67", "others"],
    )
