"""Canonical case-model for cervix cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    LymphNodeSide,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class CervixCancerCase(BaseModel):
    """Canonical extracted case record for cervix cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extracting the value of the specified items below from the given cervical cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['radical_hysterectomy', 'total_hysterectomy_bso', 'simple_hysterectomy', 'extenteration', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. radical_hysterectomy")
    surgical_technique: Literal["open", "laparoscopic", "vaginal", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. laparoscopic")
    cancer_primary_site: Literal["12_3_clock", "3_6_clock", "6_9_clock", "9_12_clock"]|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. sigmoid colon")
    histology: Literal["squamous_cell_carcinoma_hpv_associated", "squamous_cell_carcinoma_hpv_dependaent", "squamous_cell_carcinoma_nos", "adenocarcinoma_hpv_associated", "adenocarcinoma_hpv_independent", "adenocarcinoma_nos", "adenosquamous_carcinoma", "neuroendocrine_carcinoma", "glassy_cell_carcinoma", "small_cell_carcinoma", "large_cell_carcinoma", "others"]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. squamous cell carcinoma")
    grade: Literal[1,2,3]|None = GroupedField(group='nonnested', desc="identify the grade of the cancer, well->1, moderate->2, poor/undiff->3")
    tumor_size: int|None = GroupedField(group='nonnested', desc="identify the size of the tumor in mm, rounded to integer")
    depth_of_invasion_number: Literal["less_than_3", "3_to_5", "greater_than_5"]|None = GroupedField(
        group='nonnested',
        desc="identify the depth of invasion of the tumor in mm, and choose from these three categories: less_than_3, 3_to_5, greater_than_5",
    )
    depth_of_invasion_three_tier: Literal["inner_third", "middle_third", "outer_third"]|None = GroupedField(
        group='nonnested',
        desc="identify the depth of invasion of the tumor in three-tier system: inner_third, middle_third, outer_third",
    )
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---  (FIGO wording on stage_group)
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t1a1", "t1a2", "t1b1", "t1b2", "t1b3", "t2a1", "t2a2", "t2b", "t3a", "t3b", "t4"],
        pn=Literal["nx", "n0", "n1mi", "n1a", "n2mi", "n2a"],
        stage_groups={
            "stage_group": (
                Literal["0", "ia1", "ia2", "ib1", "ib2", "ib3", "iia1", "iia2", "iib", "iiia", "iiib", "iiic1", "iiic2", "iva", "ivb"],
                "identify the FIGO stage group of the tumor",
            ),
        },
    )

    # --- margins ---  (auto-expanded to list[CervixMargin])
    margins: Literal[
        "ectocervical", "endocervical", "radial_circumferential",
        "vaginal_cuff", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"distal\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"mesenteric\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[CervixLN])
    regional_lymph_node: Literal[
        "pelvic", "para_aortic", "internal_iliac", "obturator",
        "external_iliac", "common_iliac", "parametrial", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_category\": \"regional\", \"involved\": 2, \"examined\": 5}, {\"lymph_node_category\": \"mesenteric\", \"involved\": 0, \"examined\": 3}]. If not present, just output null for every lymph node",
        side=LymphNodeSide,
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
