"""Canonical case-model for colorectal cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`. Note: the registry key is ``"colorectal"``
but the synthesised nested-type names use the legacy ``Colon*`` prefix
(``ColonMargin`` / ``ColonLN`` / ``ColonBiomarker``).
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    BiomarkerSpec,
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class ColorectalCancerCase(BaseModel):
    """Canonical extracted case record for colorectal cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given colon cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given colon cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'biomarkers': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['right_hemicolectomy','extended_right_hemicolectomy','left_hemicolectomy','low_anterior_resection', 'anterior_resection', 'abdominoperineal_resection', 'total_mesorectal_excision', 'total_colectomy','subtotal_colectomy','segmental_colectomy','transanal_local_excision','polypectomy','others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. polypectomy")
    surgical_technique: Literal["open", "laparoscopic", "robotic", "ta_tme", "hybrid", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. laparoscopic")
    cancer_primary_site: Literal["cecum", "ascending_colon", "hepatic_flexure", "transverse_colon", "splenic_flexure", "descending_colon", "sigmoid_colon", "rectosigmoid_junction", "rectum", "appendix"]|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. sigmoid colon")
    histology: Literal["adenocarcinoma", "mucinous_adenocarcinoma", "signet_ring_cell_carcinoma", "medullary_carcinoma", "micropapillary_adenocarcinoma", "serrated_adenocarcinoma", "adenosquamous_carcinoma", "neuroendocrine_carcinoma",  "others"
    ]|None = GroupedField(
        group='nonnested',
        desc="identify the histological type of the cancer. e.g. adenocarcinoma, if not in the list, classify as others",
    )
    grade: int|None = GroupedField(group='nonnested', desc="identify the grade of the cancer, well->1, moderate->2, poor->3, undiff-4")
    tumor_invasion: Literal["lamina_propria", "submucosa", "muscularis_propria", "pericolorectal_tissue", "visceral_peritoneum_surface", "adjacent_organs_structures"]|None = GroupedField(group='nonnested', desc="identify the part invasioned by tumor, e.g lamina propria")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    extracellular_mucin: bool|None = GroupedField(group='nonnested', desc="check whether or not extracellular mucin is present")
    signet_ring: bool|None = GroupedField(group='nonnested', desc="check whether or not signet ring cell is present")
    tumor_budding: int|None = GroupedField(group='nonnested', desc="identify the number of tumor budding of the cancer.low->0, moderate->1, high->2")
    type_of_polyp: Literal["tubular_adenoma", "tubulovillous_adenoma", "villous_adenoma", "sessile_serrated_adenoma", "traditional_serrated_adenoma"]|None = GroupedField(group='nonnested', desc="identify the type of polyp of the tumor")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---  (custom tnm_descriptor wording; pm has 5 values)
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "tis", "t1", "t2", "t3", "t4a", "t4b"],
        pn=Literal["nx", "n0", "n1a", "n1b", "n1c", "n2a", "n2b"],
        pm=Literal["mx", "m0", "m1a", "m1b", "m1c"],
        stage_groups={
            "stage_group": Literal["0", "i", "iia", "iib", "iic", "iiia", "iiib", "iiic", "iva", "ivb", "ivc"],
        },
        tnm_descriptor_desc=(
            'identify the tnm descriptor of the tumor. e.g., "y" means post-therapy, '
            '"m" means multiple primary tumor, "r" means recurrent tumor, code this if '
            'the report explicitly mean this, dont guess'
        ),
    )

    # --- margins ---  (auto-expanded to list[ColonMargin])
    margins: Literal[
        "proximal", "distal", "mesenteric_pedicle",
        "radial_or_circumferencial", "outmost_of_adhered_tissue", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"distal\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"mesenteric\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[ColonLN]; no side; group/station wording)
    regional_lymph_node: Literal[
        "regional", "mesenteric", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_category\": \"regional\", \"involved\": 2, \"examined\": 5}, {\"lymph_node_category\": \"mesenteric\", \"involved\": 0, \"examined\": 3}]. If not present, just output null for every lymph node",
        station_name_desc="specify the name of the lymph node group/station here.",
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )

    # --- biomarkers ---  (auto-expanded to list[ColonBiomarker])
    biomarkers: list = BiomarkerSpec(
        desc="return all of the examined immunoreceptors using immunohistochemistry techniques,like mlh1, msh2, etc. in JSON format. example:{\"MSH6\": {\"expression\": true,\"percentage\": 90}, \"PMS2\": {\"expression\": true, \"percentage\": 100}},\"mlh1\": {\"expression\": true, \"percentage\": 100}}.",
        categories=Literal["mlh1", "msh2", "msh6", "pms2", "her2", "others"],
    )
