"""Canonical case-model for esophagus cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`. Note: the registry key is ``"esophagus"``
but description text uses the legacy adjective ``"esophageal"``.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class EsophagusCancerCase(BaseModel):
    """Canonical extracted case record for esophagus cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given esophagus cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given esophagus cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given esophagus cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given esophagus cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['endoscopic_resection','esophagectomy', 'esophagogastrectomy', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. polypectomy")
    surgical_technique: Literal["open", "thoracoscopic", "robotic", "hybrid", "endoscopic", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. thoracoscopic")
    cancer_primary_site: Literal['upper_third', 'middle_third', 'lower_third', 'gastroesophageal_junction']|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. upper_third")
    histology: Literal["squamous_cell_carcinoma", "adenocarcinoma", "adenoid_cystic_carcinoma", "mucoepidermoid_carcinoma", "basaloid_squamous_cell_carcinoma", "small_cell_carcinoma", "large_cell_carcinoma", "others"
    ]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. squamous cell carcinoma")
    grade: Literal[1,2,3]|None = GroupedField(group='nonnested', desc="identify the grade of the cancer, well->1, moderate->2, poor->3")
    tumor_extent: Literal['mucosa', 'submucosa', 'muscularis_propria', 'adventitia', 'adjacent_structures']|None = GroupedField(group='nonnested', desc="identify how deep the tumor invades. e.g. muscularis_propria")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t1a", "t1b", "t2", "t3", "t4a", "t4b"],
        pn=Literal["nx", "n0", "n1", "n2", "n3"],
        stage_groups={
            "stage_group": Literal["0", "i", "ia", "ib", "ic", "iia", "iib", "iiia", "iiib", "iva", "ivb"],
        },
    )

    # --- margins ---  (auto-expanded to list[EsophagusMargin])
    margins: Literal[
        "proximal", "distal", "radial", "lateral", "deep", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"distal\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"radial\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[EsophagusLN]; no side)
    regional_lymph_node: Literal[
        "regional_esophageal", "regional_gastric",
        "thoracic_1", "thoracic_1r", "thoracic_1l",
        "thoracic_4", "thoracic_4r", "thoracic_4l",
        "thoracic_7", "thoracic_8u", "thoracic_8m", "thoracic_8l", "thoracic_8",
        "thoracic_9", "thoracic_9r", "thoracic_9l",
        "thoracic_10", "thoracic_10r", "thoracic_10l",
        "abdomen_106", "abdomen_1", "abdomen_2", "abdomen_3", "abdomen_4",
        "abdomen_5", "abdomen_6", "abdomen_7", "abdomen_8", "abdomen_9", "abdomen_10",
        "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_category\": \"thoracic_1\", \"involved\": 2, \"examined\": 5}, ...]. If not present, just output null for every lymph node",
        category_desc=(
            "acceptable value for lymph node categories (i.e. stations or groups) in "
            "esophageal cancer. Default to thoracic if not mentioned. "
            "If not included in these standard lymph node 'station' number, should be "
            "classified as others."
        ),
        station_name_desc="specify the name of the lymph node station/group here.",
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
