"""Canonical case-model for liver cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

Liver is an outlier on two counts: its lymph-node nested type has
neither a category nor a side field (passed via ``LNSpec(category=None,
side=None)``), and the staging stage-group field is named
``overall_stage`` rather than ``stage_group``.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class LiverCancerCase(BaseModel):
    """Canonical extracted case record for liver cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'extent': 'You need to determine whether the tumor have extended out of liver. If so, extract list of tumor extension to one or more of the specified items below from the given hepatocellular carcinoma excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'vascular_invasion': 'You need to determine whether the tumor have vascular invasion. If so, extract list of vascular invasion to one or more of the specified items below from the given hepatocellular carcinoma excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given liver cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['wedge_resection', 'partial_hepatectomy', 'segmentectomy', 'lobectomy', 'total_hepatectomy', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. partial hepatectomy")
    tumor_site: Literal['right_lobe', 'left_lobe', 'caudate_lobe', 'quadrate_lobe', 'others']|None = GroupedField(group='nonnested', desc="identify the site of the tumor. e.g. right lobe")
    histology: Literal["hepatocellular_carcinoma","hepatocellular_carcinoma_fibrolamellar", "hepatocellular_carcinoma_scirrhous", "hepatocellular_carcinoma_clear_cell", "others"]|None = GroupedField(
        group='nonnested',
        desc="identify the histological type of the cancer. e.g. invasive carcinoma of no special type",
    )
    grade: Literal[1,2,3,4]|None = GroupedField(
        group='nonnested',
        desc="identify the grade of the cancer, well->1, moderate->2, poor->3, undifferentiated->4",
    )
    tumor_size: int|None = GroupedField(
        group='nonnested',
        desc="identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor",
    )
    tumor_focality: Literal["unifocal", "multifocal"]|None = GroupedField(group='nonnested', desc="identify whether the tumor is unifocal or multifocal")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- extent ---
    tumor_extent: list[Literal['hepatic_vein', 'portal_vein', 'visceral_peritoneum', 'gallbladder', 'diaphragm', 'others']]|None = GroupedField(
        group='extent',
        desc="return all of the possible tumor extension. example: [\"hepatic_vein\", \"gallbladder\"]. If not present, just output None, do not overdiagnosis",
    )

    # --- vascular_invasion ---
    vascular_invasion: list[Literal['large_hepatic_vein', 'large_portal_vein', 'small_vessel']]|None = GroupedField(
        group='vascular_invasion',
        desc="return all of the possible vascular invasion. example: [\"large_hepatic_vein\", \"small_vessel\"]. If not present, just output None, do not overdiagnosis",
    )

    # --- staging ---
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t1a", "t1b", "t2", "t3", "t4"],
        pn=Literal["nx", "n0", "n1"],
        stage_groups={
            "overall_stage": Literal["ia", "ib", "ii", "iiia", "iiib", "iva", "ivb"],
        },
    )

    # --- margins ---  (auto-expanded to list[LiverMargin])
    margins: Literal[
        "parenchymal", "hepatic_vein", "portal_vein", "bile_duct", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal_duodenal\", \"margin_involved\": true, \"distance\": null}, {\"margin_category\": \"anterior_outmost\", \"margin_involved\": false, \"distance\": 10}, {\"margin_category\": \"radial\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[LiverLN]; no category, no side)
    regional_lymph_node: None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"involved\": 2, \"examined\": 5, \"station_name\": \"station 1\"}, {\"involved\": 0, \"examined\": 3, \"station_name\": \"station 2\"}, ...]. If not present, just output null for every lymph node",
        category=None,
        side=None,
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
