"""Canonical case-model for lung cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

Lung is the only organ that uses :data:`LymphNodeSideRL` (right/left only,
no midline) and that has the additional ``othernested`` group carrying
the (lung-specific) ``LungHistologicalPattern`` nested type. The
biomarker shape also differs from breast/colon: ``expression`` is
required, there's no ``score`` field, and the percentage description
says "None" instead of "null".
"""
from typing import ClassVar, Literal

from pydantic import BaseModel, Field

from ._case_builder import (
    BiomarkerSpec,
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    LymphNodeSideRL,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


class LungHistologicalPattern(BaseModel):
    pattern_name: Literal[
        "acinar", "lepidic", "papillary", "solid", "micropapillary", "others",
    ] | None = Field(
        None, description="histological pattern of invasive non-mucinous adenocarcinoma"
    )
    pattern_percentage: int | None = Field(
        None, description="percentage of the histological pattern"
    )


@assemble_case_model()
class LungCancerCase(BaseModel):
    """Canonical extracted case record for lung cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'biomarkers': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'othernested': 'you need to extracting the value of the specified items below from the given pathological cancer report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['wedge_resection','segmentectomy','lobectomy','completion_lobectomy','sleeve_lobectomy','bilobectomy','pneumonectomy','major_airway_resection','others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. polypectomy")
    surgical_technique: Literal["open", "thoracoscopic", "robotic", "hybrid", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. thoracoscopic")
    sideness: Literal['right','left','midline']|None = GroupedField(group='nonnested', desc="identify which side the tumor is located. e.g. right")
    cancer_primary_site: Literal['upper_lobe', 'middle_lobe', 'lower_lobe', 'main_bronchus', 'bronchus_intermedius', 'bronchus_lobar', 'others']|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. upper_lobe")
    tumor_focality: Literal['single_focus', 'separate_in_same_lobe_t3', 'separate_nodule_in_ipsilateral_t4', 'separate_nodule_in_contralateral_m1a']|None = GroupedField(
        group='nonnested',
        desc="identify whether the tumor is single focus or multiple foci; this is important for t and m category",
    )
    histology: Literal["adenocarcinoma", "squamous_cell_carcinoma", "adenosquamous_carcinoma", "large_cell_carcinoma", "large_cell_neuroendocrine_carcinoma", "small_cell_carcinoma", "carcinoid_tumor", "sarcomatoid_carcinoma", "pleomorphic_carcinoma", "pulmonary_lymphoepithelioma_like_carcinoma", "mucoepidermoid_carcinoma", "salivary_gland_type_tumor", "non_small_cell_carcinoma_not_specified", "non_small_cell_carcinoma_with_neuroendocrine_features", "other"
    ]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. adenocarcinoma")
    grade: int|None = GroupedField(group='nonnested', desc="identify the grade of the cancer, well->1, moderate->2, poor->3, undiff->4")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    spread_through_air_spaces_stas: bool|None = GroupedField(group='nonnested', desc="check whether or not spread through air spaces (STAS) is present")
    visceral_pleural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not visceral pleural invasion is present")
    direct_invasion_of_adjacent_structures: bool|None = GroupedField(group='nonnested', desc="check whether or not direct invasion of adjacent structures is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "tis", "t1mi", "t1a", "t1b", "t1c", "t2a", "t2b", "t3", "t4"],
        pn=Literal["nx", "n0", "n1", "n2", "n3"],
        pm=Literal["mx", "m0", "m1a", "m1b", "m1c"],
        stage_groups={
            "stage_group": Literal["0", "ia1", "ia2", "ia3", "ib", "iia", "iib", "iiia", "iiib", "iiic", "iva", "ivb", "ivc"],
        },
    )

    # --- margins ---  (auto-expanded to list[LungMargin])
    margins: Literal[
        "bronchial", "vascular", "parenchymal", "chest_wall", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"bronchial\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"vascular\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"parenchymal\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[LungLN]; R/L only - no midline)
    regional_lymph_node: Literal[
        "peribronchial",
        "1", "2", "4", "5", "6", "8", "9", "10", "11", "12", "13", "14",
        "3a", "3p", "7", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_side\": \"right\", \"lymph_node_category\": \"4\", \"involved\": 2, \"examined\": 5}, {\"lymph_node_side\": \"left\", \"lymph_node_category\": \"7\", \"involved\": 0, \"examined\": 3}]. If not present, just output null for every lymph node",
        side=LymphNodeSideRL,
        category_desc=(
            "acceptable value for lymph node categories (i.e. stations or groups) in "
            "lung cancer. If not included in these standard lymph node 'stations'/'groups' "
            "should be classified as others."
        ),
        station_name_desc="specify the name of the lymph node station/group here.",
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )

    # --- biomarkers ---  (auto-expanded to list[LungBiomarker]; expression required, no score)
    biomarkers: list = BiomarkerSpec(
        desc="return all of the examined biomarkers using immunohistochemistry techniques,like alk, ros1, pd-l1. in JSON format. example:[{\"biomarker_category\": \"ALK\", \"expression\": true, \"percentage\": 70}, {\"biomarker_category\": \"PDL1\", \"expression\": false, \"percentage\": 0}]. If not present, just output None for every biomarker",
        categories=Literal["ALK", "ROS1", "PDL1", "others"],
        expression_required=True,
        has_score=False,
        percentage_null_word="None",
    )

    # --- othernested ---
    histological_patterns: list[LungHistologicalPattern]|None = GroupedField(
        group='othernested',
        desc="if the histology is invasive non-mucinous adenocarcinoma, please identify all of the histological patterns and its percentage. if not, return None",
    )
