"""Canonical case-model for pancreas cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class PancreasCancerCase(BaseModel):
    """Canonical extracted case record for pancreas cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given pancreas cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given pancreas cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given pancreas cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given pancreas cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['partial_pancreatectomy', 'ssppd', 'pppd', 'whipple_procedure', 'distal_pancreatectomy', 'total_pancreatectomy', 'others']|None = GroupedField(
        group='nonnested',
        desc="identify which surgery procedure was used. e.g. partial pancreatectomy, pylorus-preserving pancreaticoduodenectomy(PPPD), Subtotal stomach-preserving pancreaticoduodenectomy (SSPPD), Whipple procedure, etc.",
    )
    tumor_site: Literal["head", "neck", "body", "tail", "uncinate_process", "others"]|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. head of pancreas")
    histology: Literal["ductal_adenocarcinoma_nos", "ipmn_with_carcinoma", "itpn_with_carcinoma", "acinar_cell_carcinoma", "solid_pseudopapillary_neoplasm", "undifferentiated_carcinoma", "others"]|None = GroupedField(
        group='nonnested',
        desc="identify the histological type of the cancer. e.g. invasive carcinoma of no special type",
    )
    tumor_size: int|None = GroupedField(
        group='nonnested',
        desc="identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor",
    )
    tumor_extension: Literal["within_pancreas", "peripancreatic_soft_tissue", "adjacent_organs_structures", "others"]|None = GroupedField(group='nonnested', desc="identify the extent of tumor extension. e.g. within pancreas")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---  (pm has only mx/m1; stage_group field name is overall_stage)
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "tis", "t1a", "t1b", "t1c", "t2", "t3", "t4"],
        pn=Literal["nx", "n0", "n1", "n2"],
        pm=Literal["mx", "m1"],
        stage_groups={
            "overall_stage": Literal["ia", "ib", "iia", "iib", "iii", "iv"],
        },
    )

    # --- margins ---  (auto-expanded to list[PancreasMargin])
    margins: Literal[
        "distal_pancreatic", "proximal_pancreatic", "pancreatic_neck",
        "uncinate", "bile_duct",
        "proximal_gastric", "proximal_duodenal", "distal_intestinal",
        "outmost", "anterior_outmost", "posterior_outmost", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal_duodenal\", \"margin_involved\": true, \"distance\": null}, {\"margin_category\": \"anterior_outmost\", \"margin_involved\": false, \"distance\": 10}, {\"margin_category\": \"radial\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[PancreasLN]; no side)
    regional_lymph_node: Literal[
        "regional_pancreatic", "regional_gastric",
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14",
        "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_category\": \"1\", \"involved\": 2, \"examined\": 5, \"station_name\": \"station 1\"}, {\"lymph_node_category\": \"2\", \"involved\": 0, \"examined\": 3, \"station_name\": \"station 2\"}, ...]. If not present, just output null for every lymph node",
        station_name_desc="specify the name of the lymph node station/group here.",
    )
    extranodal_extension: bool|None = GroupedField(group='lymph_nodes', desc="check whether or not extranodal extension is present")
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer. if not, return None",
    )
