"""Canonical case-model for prostate cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

Prostate is the only organ with a non-standard ``margins`` group:
``margin_positivity`` (bool), ``involved_margin_list`` (list of Literal
sites), ``margin_length``. These stay declared inline as plain
``GroupedField`` fields rather than going through :class:`MarginSpec`.
``pm_category`` also has 5 values rather than the default 3.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    LymphNodeSide,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class ProstateCancerCase(BaseModel):
    """Canonical extracted case record for prostate cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given prostate cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given prostate cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given prostate cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given prostate cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['radical_prostatectomy','others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. radical prostatectomy")
    surgical_technique: Literal["open", "robotic", "hybrid", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. robotic")
    prostate_weight: int|None = GroupedField(group='nonnested', desc="identify the weight of the prostate in grams. e.g. 50")
    prostate_size: int|None = GroupedField(group='nonnested', desc="identify the size of the prostate in mm, largest dimension. e.g. 45 means 45mm")
    histology: Literal[
        "acinar_adenocarcinoma",
        "intraductal_carcinoma",
        "ductal_adenocarcinoma",
        "mixed_acinar_ductal",
        "neuroendocrine_carcinoma_small_cell",
        "others"
    ]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. acinar adenocarcinoma")
    grade: Literal["group_1_3_3", "group_2_3_4", "group_3_4_3", "group_4_4_4", "group_5_4_5", "group_5_5_4", "group_5_5_5"]|None = GroupedField(
        group='nonnested',
        desc="identify the gleason group of the cancer. e.g. group_2_3_4 means gleason score 7 (3+4)",
    )
    gleason_4_percentage: int|None = GroupedField(group='nonnested', desc="identify the percentage of gleason pattern 4. e.g. 20 means 20%")
    gleason_5_percentage: int|None = GroupedField(group='nonnested', desc="identify the percentage of gleason pattern 5. e.g. 0 means 0%")
    intraductal_carcinoma_presence: bool|None = GroupedField(group='nonnested', desc="check whether or not intraductal carcinoma is present")
    cribriform_pattern_presence: bool|None = GroupedField(group='nonnested', desc="check whether or not cribriform pattern is present. only in gleason score 7 or 8")
    tumor_percentage: int|None = GroupedField(
        group='nonnested',
        desc="identify the percentage of tumor in the prostate in both lobes. e.g. 30 means 30%",
    )
    tumor_size: int|None = GroupedField(group='nonnested', desc="identify the size of the tumor in mm, largest dimension. e.g. 15 means 15mm")
    extraprostatic_extension: bool|None = GroupedField(group='nonnested', desc="check whether or not extraprostatic extension is present")
    seminal_vesicle_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not seminal vesicle invasion is present")
    bladder_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not bladder invasion is present")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---  (pm has 5 values)
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t2", "t3a", "t3b", "t4"],
        pn=Literal["nx", "n0", "n1"],
        pm=Literal["mx", "m0", "m1a", "m1b", "m1c"],
        stage_groups={
            "stage_group": Literal["0", "i", "iia", "iib", "iic", "iiia", "iiib", "iiic", "iva", "ivb"],
        },
    )

    # --- margins ---  (non-standard shape — kept inline as plain GroupedField)
    margin_positivity: bool|None = GroupedField(group='margins', desc="check whether or not any margin is positive")
    involved_margin_list: list[Literal[
        "right_apical",
        "left_apical",
        "right_bladder_neck",
        "left_bladder_neck",
        "right_anterior",
        "left_anterior",
        "right_lateral",
        "left_lateral",
        "right_posterolateral",
        "left_posterolateral",
        "right_posterior",
        "left_posterior"
    ]] | None = GroupedField(group='margins', desc="list of involved margins")
    margin_length: Literal["limited", "non_limited"]|None = GroupedField(
        group='margins',
        desc="if margin is positive, check whether the length of positive margin is limited (<3mm) or non-limited (>=3mm)",
    )

    # --- lymph_nodes ---  (auto-expanded to list[ProstateLN])
    regional_lymph_node: Literal[
        "hypogastric", "obturator", "external_iliac", "internal_iliac",
        "common_iliac", "iliac_nos", "pelvic_nos", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_side\": \"right, \"lymph_node_category\": \"internal_iliac\", \"involved\": 2, \"examined\": 5}, ...]. If not present, just output null for every lymph node",
        side=LymphNodeSide,
        category_desc=(
            "acceptable value for lymph node categories (i.e. stations) in prostate cancer. "
            "If not included in these standard lymph node 'station' number, should be "
            "classified as others."
        ),
        station_name_desc="specify the name of the lymph node group/station here.",
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
