"""Canonical case-model for stomach cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class StomachCancerCase(BaseModel):
    """Canonical extracted case record for stomach cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given stomach cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given stomach cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given stomach cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given stomach cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    procedure: Literal['endoscopic_resection','partial_gastrectomy', 'total_gastrectomy', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. polypectomy")
    surgical_technique: Literal["open", "laparoscopic", "robotic", "hybrid", "others"]|None = GroupedField(group='nonnested', desc="identify how the surgery was taken. e.g. laparoscopic")
    cancer_primary_site: Literal['cardia', 'fundus', 'body', 'antrum', 'pylorus', 'others']|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. antrum")
    histology: Literal["tubular_adenocarcinoma", "poorly_cohesive_carcinoma", "mixed_tubular_poorly_cohesive", "mucinous_adenocarcinoma", "mixed_mucinous_poorly_cohesive", "hepatoid_carcinoma", "others"]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. tubular adenocarcinoma")
    grade: Literal[1,2,3]|None = GroupedField(group='nonnested', desc="identify the grade of the cancer, well->1, moderate->2, poor->3")
    tumor_extent: Literal['lamina_propria', 'muscularis_mucosae', 'submucosa', 'muscularis_propria', "penetrate_subserosal_connective_tissue_no_serosa", 'invades_serosa_without_adjacent_structure_invasion', 'invades_adjacent_structures']|None = GroupedField(
        group='nonnested',
        desc="identify how deep the tumor invades. e.g. penetrate_subserosal_connective_tissue_no_serosa for a t3 tumor",
    )
    extracellular_mucin: bool|None = GroupedField(group='nonnested', desc="check whether or not extracellular mucin is present")
    signet_ring: bool|None = GroupedField(group='nonnested', desc="check whether or not signet ring cell is present")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t1a", "t1b", "t2", "t3", "t4a", "t4b"],
        pn=Literal["nx", "n0", "n1", "n2", "n3a", "n3b"],
        stage_groups={
            "stage_group": Literal["0", "i", "ii", "iii", "iv", "ia", "ib", "iia", "iib", "iiia", "iiib", "iiic"],
        },
    )

    # --- margins ---  (auto-expanded to list[StomachMargin])
    margins: Literal[
        "proximal", "distal", "radial", "lateral", "deep", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[{\"margin_category\": \"proximal\", \"margin_involved\": true, \"distance\": 5}, {\"margin_category\": \"distal\", \"margin_involved\": false, \"distance\": null}, {\"margin_category\": \"radial\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[StomachLN]; uses "groups" wording)
    regional_lymph_node: Literal[
        "regional", "regional_lesser_curv", "regional_greater_curv",
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_category\": \"1\", \"involved\": 2, \"examined\": 5, \"station_name\": \"station 1\"}, {\"lymph_node_category\": \"2\", \"involved\": 0, \"examined\": 3, \"station_name\": \"station 2\"}, ...]. If not present, just output null for every lymph node",
        category_desc=(
            "acceptable value for lymph node groups in stomach cancer. "
            "If not included in these standard lymph node groups, should be classified "
            "as others."
        ),
        station_name_desc="specify the name of the lymph node group here.",
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
