"""Canonical case-model for thyroid cancer (v2, schema-driven).

SINGLE SOURCE OF TRUTH. DSPy signatures are built dynamically from the
fields below by ``digital_registrar_research.signatures.factory``;
JSON Schema is auto-generated by the ``registrar-schemas`` CLI.

The lean ``<Organ>CancerCase`` declares only the per-organ vocabularies
and overrides; the verbose Pydantic class is built by
:func:`assemble_case_model`.
"""
from typing import ClassVar, Literal

from pydantic import BaseModel

from ._case_builder import (
    DEFAULT_GROUP_INSTRUCTION,
    GroupedField,
    LNSpec,
    LymphNodeSide,
    MarginSpec,
    StagingSpec,
    assemble_case_model,
)


@assemble_case_model()
class ThyroidCancerCase(BaseModel):
    """Canonical extracted case record for thyroid cancer."""

    _GROUP_INSTRUCTIONS: ClassVar[dict[str, str]] = {
        'nonnested': 'you need to extract the value of the specified items below from the given pancreas cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'staging': 'you need to extract the value of the specified items below from the given thyroid cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'margins': 'you need to extract the value of the specified items below from the given thyroid cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
        'lymph_nodes': 'you need to extract the value of the specified items below from the given thyroid cancer excision report' + ' ' + DEFAULT_GROUP_INSTRUCTION,
    }

    # --- nonnested ---
    predisposing_condition: Literal["radiation", "family_history"]|None = GroupedField(
        group='nonnested',
        desc="identify any predisposing condition mentioned in the report, such as \"Hashimoto thyroiditis\" or \"radiation exposure\". If none mentioned, return None",
    )
    procedure: Literal['partial_excision', 'right_lobectomy', 'left_lobectomy', 'total_thyroidectomy', 'others']|None = GroupedField(group='nonnested', desc="identify which surgery procedure was used. e.g. partial thyroidectomy")
    tumor_focality: Literal["unifocal", "multifocal", "not_specified"]|None = GroupedField(
        group='nonnested',
        desc="identify whether the tumor is unifocal or multifocal. If not specified, return not_specified",
    )
    tumor_site: Literal["right_lobe", "left_lobe", "isthmus", "both_lobe", "others"]|None = GroupedField(group='nonnested', desc="identify the primary site of cancer. e.g. right lobe of thyroid")
    histology: Literal["papillary_thyroid_carcinoma", "follicular_thyroid_carcinoma", "medullary_thyroid_carcinoma", "anaplastic_thyroid_carcinoma", "others"]|None = GroupedField(group='nonnested', desc="identify the histological type of the cancer. e.g. papillary thyroid carcinoma")
    tumor_size: int|None = GroupedField(
        group='nonnested',
        desc="identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor",
    )
    mitotic_activity: Literal["less_than_3", "3_to_5", "more_than_5"]|None = GroupedField(
        group='nonnested',
        desc="identify the mitotic activity of the tumor, in mitoses per 10 high power fields. if not specified, return null",
    )
    extrathyroid_extension: Literal["microscopic_strap_muscle", "macroscopic_strap_muscle_t3b", "subcutaneous_trachea_esophagus_rln_t4a", "prevertebral_carotid_mediastinal_t4b"]|None = GroupedField(
        group='nonnested',
        desc="identify if clinically extrathyroid extension is present, only four categories are allowed, if none specified, return None",
    )
    tumor_necrosis: bool|None = GroupedField(group='nonnested', desc="check whether or not tumor necrosis is present")
    lymphovascular_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not lymphovascular invasion is present")
    perineural_invasion: bool|None = GroupedField(group='nonnested', desc="check whether or not perineural invasion is present")
    distant_metastasis: bool|None = GroupedField(group='nonnested', desc="check whether or not distant metastasis is present")
    treatment_effect: str|None = GroupedField(
        group='nonnested',
        desc="check the treatment effect of the cancer. If you see \"No known presurgical therapy\", return None",
    )

    # --- staging ---
    _STAGING: ClassVar = StagingSpec(
        pt=Literal["tx", "t1a", "t1b", "t2", "t3a", "t3b", "t4a", "t4b"],
        pn=Literal["nx", "n0", "n1a", "n1b"],
        stage_groups={
            "overall_stage": Literal["i", "ii", "iii", "iva", "ivb", "ivc"],
        },
    )

    # --- margins ---  (auto-expanded to list[ThyroidMargin])
    margins: Literal[
        "outmost", "anterior_outmost", "posterior_outmost", "isthmus", "others",
    ] | None = MarginSpec(
        desc="return all of the possible involved margins and its distance from cancer. example:[ {\"margin_category\": \"anterior_outmost\", \"margin_involved\": false, \"distance\": 10}, {\"margin_category\": \"isthmus\", \"margin_involved\": false, \"distance\": null}]. If not present, just output null for every margin",
    )

    # --- lymph_nodes ---  (auto-expanded to list[ThyroidLN])
    regional_lymph_node: Literal[
        "level_vi_central", "level_i", "level_ii", "level_iii",
        "level_iv", "level_v", "level_vii", "others",
    ] | None = LNSpec(
        desc="return all of the involved regional lymph node. example:[{\"lymph_node_side\": \"left\", \"lymph_node_category\": \"level_vi_central\", \"involved\": 2, \"examined\": 5, \"station_name\": \"station 6\"}, {\"lymph_node_side\": \"right\", \"lymph_node_category\": \"level_ii\", \"involved\": 0, \"examined\": 3, \"station_name\": \"station 6\"}, ...]. If not present, just output null for every lymph node",
        side=LymphNodeSide,
    )
    extranodal_extension: bool|None = GroupedField(
        group='lymph_nodes',
        desc="check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    )
    maximal_ln_size: int|None = GroupedField(
        group='lymph_nodes',
        desc="check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    )
