"""Path-glob → handler dispatch for non-case files (configs, splits, logs, blobs, etc.).

Case-structured files (reports, annotations, preannotations, predictions) are
generated by the orchestrator from the case index, NOT routed through here.
"""
from __future__ import annotations

from pathlib import Path

from .handlers import (
    blob_to_placeholder, csv_case_ids, log_banner,
    manifest_yaml, passthrough, skip, splits,
)
from .manifest import Manifests


_BLOB_EXTS = {".pt", ".bin", ".safetensors", ".onnx", ".gguf", ".pth"}
_LOG_NAMES = {"_run.log", "_log.jsonl"}


def route(src: Path, src_root: Path, out_root: Path, manifests: Manifests,
          *, master_seed: int, id_map: dict[str, str]) -> None:
    """Dispatch one non-case file to its handler."""
    rel = src.relative_to(src_root)
    rel_posix = rel.as_posix()
    dst = out_root / rel

    # Pre-skip the obfuscator's own output manifests.
    if rel.parts and rel.parts[0] in {"_obfuscator_outputs.json", "_obfuscator_skipped.json"}:
        return

    # 1. Configs verbatim.
    if rel_posix.startswith("configs/") and rel.suffix in (".yaml", ".yml"):
        return passthrough.handle(src, dst, manifests)

    # 2. Model checkpoints — placeholder.
    if rel_posix.startswith("models/") and rel.suffix in _BLOB_EXTS:
        return blob_to_placeholder.handle(src, dst, manifests)

    # 3. Model configs/placeholders — verbatim.
    if rel_posix.startswith("models/") and (rel.suffix in (".yaml", ".yml", ".placeholder")):
        return passthrough.handle(src, dst, manifests)

    # 4. .gitkeep — verbatim (preserve dir skeleton).
    if rel.name == ".gitkeep":
        return passthrough.handle(src, dst, manifests)

    # 5. Logs / jsonl logs — banner.
    if rel.name in _LOG_NAMES or rel.suffix == ".log" or rel.suffix == ".jsonl":
        return log_banner.handle(src, dst, manifests)

    # 6. splits.json under data/.
    if rel_posix.startswith("data/") and rel.name == "splits.json":
        return splits.handle(src, dst, manifests, master_seed, id_map)

    # 7. dataset_manifest.yaml under data/.
    if rel_posix.startswith("data/") and rel.name == "dataset_manifest.yaml":
        return manifest_yaml.handle(src, dst, manifests, id_map)

    # 8. CSV files with case IDs.
    if rel.suffix == ".csv" and "case_id" in rel.name.lower():
        return csv_case_ids.handle(src, dst, manifests, master_seed)

    # 9. Run metadata files (_summary.json, _run_meta.json) under predictions —
    #    overwritten by orchestrator.write_predictions_run_metadata; skip silently.
    if "results/predictions/" in rel_posix and rel.name in (
        "_summary.json", "_run_meta.json", "_manifest.yaml"
    ):
        return  # orchestrator handles these

    # 10. README.md — verbatim (no PHI by design).
    if rel.name == "README.md":
        return passthrough.handle(src, dst, manifests)

    # Default: skip + record.
    skip.handle(src, manifests, reason=f"unrouted file type ({rel.suffix or 'no-ext'})")
