"""Extraction metadata for stomach cancer (Layer 2 of the three-layer schema).

Layer 1 (shape & enums): :mod:`schemas.pydantic.stomach`.
Layer 3 (surface-form aliases): :file:`schemas/aliases/stomach.toml` (optional).

EDIT THIS FILE FOR:
  - per-field ``desc`` strings (LM-facing explanations of what to extract).
  - ``GROUP_INSTRUCTIONS`` (per-decomposition-group framing).

DO NOT EDIT THIS FILE FOR:
  - surface-form aliases / synonyms / clone names — those live in
    ``schemas/aliases/stomach.toml`` and are merged into ``FIELD_META``
    at registry-build time. Any ``value_hints`` key added here will be
    discarded with a ``UserWarning`` by ``_build_organ_meta`` in
    :mod:`schemas.extraction`.
"""
from __future__ import annotations

from ..pydantic._factory_helpers import DEFAULT_GROUP_INSTRUCTION
from . import FieldMeta

GROUP_INSTRUCTIONS: dict[str, str] = {
    "nonnested":   "you need to extract the value of the specified items below from the given stomach cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "staging":     "you need to extract the value of the specified items below from the given stomach cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "margins":     "you need to extract the value of the specified items below from the given stomach cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "lymph_nodes": "you need to extract the value of the specified items below from the given stomach cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
}


FIELD_META: dict[str, FieldMeta] = {
    # --- nonnested ---
    "procedure":          {"group": "nonnested", "desc": "identify which surgery procedure was used. e.g. polypectomy"},
    "surgical_technique": {"group": "nonnested", "desc": "identify how the surgery was taken. e.g. laparoscopic"},
    "cancer_primary_site":{"group": "nonnested", "desc": "identify the primary site of cancer. e.g. antrum"},
    "histology":          {"group": "nonnested", "desc": "identify the histological type of the cancer. e.g. tubular adenocarcinoma"},
    "grade":              {"group": "nonnested", "desc": "identify the grade of the cancer, well->1, moderate->2, poor->3"},
    "tumor_extent":       {"group": "nonnested", "desc": "identify how deep the tumor invades. e.g. penetrate_subserosal_connective_tissue_no_serosa for a t3 tumor"},
    "extracellular_mucin":     {"group": "nonnested", "desc": "check whether or not extracellular mucin is present"},
    "signet_ring":             {"group": "nonnested", "desc": "check whether or not signet ring cell is present"},
    "lymphovascular_invasion": {"group": "nonnested", "desc": "check whether or not lymphovascular invasion is present"},
    "perineural_invasion":     {"group": "nonnested", "desc": "check whether or not perineural invasion is present"},
    "distant_metastasis":      {"group": "nonnested", "desc": "check whether or not distant metastasis is present"},
    "treatment_effect": {
        "group": "nonnested",
        "desc": 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None',
    },

    # --- staging ---
    "tnm_descriptor": {
        "group": "staging",
        "desc": 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.',
    },
    "pt_category":  {"group": "staging", "desc": "identify the pt category of the tumor"},
    "pn_category":  {"group": "staging", "desc": "identify the pn category of the tumor"},
    "pm_category": {
        "group": "staging",
        "desc": "identify the pm category of the tumor. if you see cM0 or cM1, etc., code as mx, since pathological M category is not available",
    },
    "stage_group":  {"group": "staging", "desc": "identify the stage group of the tumor"},
    "ajcc_version": {"group": "staging", "desc": "identify the ajcc version of the pathological staging"},

    # --- margins ---
    "margins": {
        "group": "margins",
        "desc": 'return all of the possible involved margins and its distance from cancer. example:[{"margin_category": "proximal", "margin_involved": true, "distance": 5}, {"margin_category": "distal", "margin_involved": false, "distance": null}, {"margin_category": "radial", "margin_involved": false, "distance": null}]. If not present, just output null for every margin',
    },
    "margins.margin_category": {
        "desc": "acceptable value for surgical margins in stomach cancer. If not included in these standard margins, should be classified as others.",
    },
    "margins.distance": {
        "desc": "If margin is involved, return 0. If margin is uninvolved/free, try your best to find the distance at both microscopic and macroscopic(gross) description, and specify the distance from tumor to margin in mm, rounded to integer. If the margin is uninvolved/free and, after your best effort, the distance is still not specified, return null",
    },

    # --- lymph_nodes (no side, "groups" wording) ---
    "regional_lymph_node": {
        "group": "lymph_nodes",
        "desc": 'return all of the involved regional lymph node. example:[{"lymph_node_category": "1", "involved": 2, "examined": 5, "station_name": "station 1"}, {"lymph_node_category": "2", "involved": 0, "examined": 3, "station_name": "station 2"}, ...]. If not present, just output null for every lymph node',
    },
    "regional_lymph_node.lymph_node_category": {
        "desc": "acceptable value for lymph node groups in stomach cancer. If not included in these standard lymph node groups, should be classified as others.",
    },
    "regional_lymph_node.station_name": {
        "desc": "specify the name of the lymph node group here.",
    },
    "extranodal_extension": {
        "group": "lymph_nodes",
        "desc": "check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    },
    "maximal_ln_size": {
        "group": "lymph_nodes",
        "desc": "check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    },
}


__all__ = ["FIELD_META", "GROUP_INSTRUCTIONS"]
