"""Extraction metadata for breast cancer (Layer 2 of the three-layer schema).

Layer 1 (clean Pydantic shape): :mod:`schemas.pydantic.breast`.
Layer 3 (surface-form aliases): :file:`schemas/aliases/breast.toml` (optional).

Conventions
-----------
- Every field in :class:`BreastCancerCase` (post ``@assemble_case_model``
  expansion) MUST have a corresponding ``FIELD_META`` entry. The Phase-1
  invariant is that the descriptions match the legacy
  ``GroupedField(desc=...)`` strings byte-for-byte so ``data/breast.json``
  stays compatible with downstream consumers.
- Nested ``$defs`` sub-fields use a dotted key (``"biomarkers.percentage"``).
- ``GROUP_INSTRUCTIONS`` insertion order doubles as the canonical
  extraction order (mirrors the legacy ``_GROUP_INSTRUCTIONS`` ClassVar
  on the case-model).

EDIT THIS FILE FOR:
  - per-field ``desc`` strings (LM-facing explanations of what to extract).
  - ``GROUP_INSTRUCTIONS`` (per-decomposition-group framing).

DO NOT EDIT THIS FILE FOR:
  - surface-form aliases / synonyms / clone names — those live in
    ``schemas/aliases/breast.toml`` and are merged into ``FIELD_META``
    at registry-build time. Any ``value_hints`` key added here will be
    discarded with a ``UserWarning`` by ``_build_organ_meta`` in
    :mod:`schemas.extraction`.
"""
from __future__ import annotations

from ..pydantic._factory_helpers import DEFAULT_GROUP_INSTRUCTION
from . import FieldMeta

GROUP_INSTRUCTIONS: dict[str, str] = {
    "nonnested":   "you need to extract the value of the specified items below from the given breast cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "dcis":        "You need to extract data about ductal carcinoma in situ below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "grading":     "you need to extract the value of the specified items below from the given breast cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "staging":     "you need to extract the value of the specified items below from the given breast cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "margins":     "you need to extract the value of the specified items below from the given breast cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "lymph_nodes": "you need to extract the value of the specified items below from the given breast cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "biomarkers":  "you need to extract breast cancer biomarkers, which is very important, below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
}


_BIOMARKERS_PARENT_DESC = (
    'return all of the examined immunoreceptors using immunohistochemistry techniques,'
    'like er, pr, her2, ki67, etc. in a list of pydantic structures,\n'
    '    example: [{"biomarker_category": "er", "expression": true, "percentage": 90, "score": null, "biomarker_name": "estrogen receptor"},\n'
    '    {"biomarker_category": "pr", "expression": false, "percentage": 0, "score": null, "biomarker_name": "progesterone receptor"},\n'
    '    {"biomarker_category": "her2", "expression": null, "percentage": 0, "score": 2, "biomarker_name": "human epidermal growth factor receptor 2"},\n'
    '    {"biomarker_category": "ki67", "expression": null, "percentage": 30, "score": null, "biomarker_name": "ki67 proliferation index"}]. '
    'If not present, just output null for every biomarker'
)

_MARGINS_PARENT_DESC = (
    'return all of the possible involved margins and its distance from cancer. '
    'example:[{"margin_category": "proximal", "margin_involved": true, "distance": 5}, '
    '{"margin_category": "distal", "margin_involved": false, "distance": null}, '
    '{"margin_category": "radial", "margin_involved": false, "distance": null}]. '
    'If not present, just output null for every margin'
)

_LN_PARENT_DESC = (
    'return all of the involved regional lymph node. '
    'example:[{"lymph_node_side": "right", "lymph_node_category": "sentinel", "involved": 2, "examined": 5, "station_name": "station 1"}, '
    '{"lymph_node_side": "left", "lymph_node_category": "nonsentinel", "involved": 0, "examined": 3, "station_name": "station 2"}, ...]. '
    'If not present, just output null for every lymph node'
)


FIELD_META: dict[str, FieldMeta] = {
    # --- nonnested ---
    "procedure": {
        "group": "nonnested",
        "desc": "identify which surgery procedure was used. e.g. partial mastectomy",
    },
    "cancer_quadrant": {
        "group": "nonnested",
        "desc": "identify the primary site of cancer. e.g. upper outer quadrant. please consider what side is the breast excision specimen when you determine the quadrant",
    },
    "cancer_clock": {
        "group": "nonnested",
        "desc": "identify the clock position of the cancer if mentioned. e.g. 3",
    },
    "cancer_laterality": {
        "group": "nonnested",
        "desc": "identify the side of the cancer. e.g. right",
    },
    "histology": {
        "group": "nonnested",
        "desc": "identify the histological type of the cancer. e.g. invasive carcinoma of no special type. If the histological type is not included in the above list, please code as other_special_types and specify the histological type in the description field.",
    },
    "tumor_size": {
        "group": "nonnested",
        "desc": "identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor",
    },
    "lymphovascular_invasion": {
        "group": "nonnested",
        "desc": "check whether or not lymphovascular invasion is present",
    },
    "perineural_invasion": {
        "group": "nonnested",
        "desc": "check whether or not perineural invasion is present",
    },
    "distant_metastasis": {
        "group": "nonnested",
        "desc": "check whether or not distant metastasis is present",
    },
    "treatment_effect": {
        "group": "nonnested",
        "desc": 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None',
    },

    # --- dcis ---
    "dcis_present": {
        "group": "dcis",
        "desc": "check whether or not ductal carcinoma in situ is present",
    },
    "dcis_size": {
        "group": "dcis",
        "desc": "if ductal carcinoma in situ is present, identify the size of the largest DCIS in mm, rounded",
    },
    "dcis_comedo_necrosis": {
        "group": "dcis",
        "desc": "if ductal carcinoma in situ is present, check whether or not comedo necrosis is present",
    },
    "dcis_grade": {
        "group": "dcis",
        "desc": "if ductal carcinoma in situ is present, identify the grade of DCIS, low grade (grade 1), intermediate grade (grade 2), high grade (grade 3)",
    },

    # --- grading ---
    "nuclear_grade":    {"group": "grading", "desc": "identify the nuclear grade of the tumor"},
    "tubule_formation": {"group": "grading", "desc": "identify the tubule formation score of the tumor"},
    "mitotic_rate":     {"group": "grading", "desc": "identify the mitotic rate score of the tumor"},
    "total_score":      {"group": "grading", "desc": "identify the total score of the tumor"},
    "grade":            {"group": "grading", "desc": "identify the grade of the tumor"},

    # --- staging (field names from StagingSpec.iter_field_names()) ---
    "tnm_descriptor": {
        "group": "staging",
        "desc": 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.',
    },
    "pt_category": {"group": "staging", "desc": "identify the pt category of the tumor"},
    "pn_category": {"group": "staging", "desc": "identify the pn category of the tumor"},
    "pm_category": {
        "group": "staging",
        "desc": "identify the pm category of the tumor. if you see cM0 or cM1, etc., code as mx, since pathological M category is not available",
    },
    "pathologic_stage_group": {
        "group": "staging",
        "desc": "identify the pathologic stage group of the tumor, return none if only anatomical stage group is given, dont guess",
    },
    "anatomic_stage_group": {
        "group": "staging",
        "desc": "identify the anatomic stage group of the tumor",
    },
    "ajcc_version": {
        "group": "staging",
        "desc": "identify the ajcc version of the pathological staging",
    },

    # --- margins ---
    "margins": {"group": "margins", "desc": _MARGINS_PARENT_DESC},
    "margins.margin_category": {
        "desc": "acceptable value for surgical margins in breast cancer. If not included in these standard margins, should be classified as others.",
    },
    "margins.distance": {
        "desc": "If margin is involved, return 0. If margin is uninvolved/free, try your best to find the distance at both microscopic and macroscopic(gross) description, and specify the distance from tumor to margin in mm, rounded to integer. If the margin is uninvolved/free and, after your best effort, the distance is still not specified, return null",
    },

    # --- lymph_nodes ---
    "regional_lymph_node": {"group": "lymph_nodes", "desc": _LN_PARENT_DESC},
    "regional_lymph_node.lymph_node_side": {
        "desc": "acceptable value for lymph node side in breast cancer. If not included in these standard sides, should be classified as None.",
    },
    "regional_lymph_node.lymph_node_category": {
        "desc": "acceptable value for lymph node categories (i.e. stations) in breast cancer. If not included in these standard lymph node 'station' number, should be classified as others.",
    },
    "regional_lymph_node.station_name": {
        "desc": "specify the name of the lymph node station here.",
    },
    "extranodal_extension": {
        "group": "lymph_nodes",
        "desc": "check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    },
    "maximal_ln_size": {
        "group": "lymph_nodes",
        "desc": "check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    },

    # --- biomarkers ---
    "biomarkers": {"group": "biomarkers", "desc": _BIOMARKERS_PARENT_DESC},
    "biomarkers.biomarker_category": {
        "desc": "acceptable value for biomarker categories in breast cancer. If not included in these standard categories, should be classified as others.",
    },
    "biomarkers.expression": {
        "desc": "specify whether or not the biomarker is expressed here. For Her-2 please refer to the score field, and don't fill in this field.",
    },
    "biomarkers.percentage": {
        "desc": "the percentage of tumor cells showing positive expression of the biomarker, rounded to integer. if not specified, return null",
    },
    "biomarkers.score": {
        "desc": "specify the Her-2 expression score, negative: score 0 or 1, equivocal: score 2, positive: score 3 of the biomarker here, if applicable.",
    },
    "biomarkers.biomarker_name": {
        "desc": "specify the name of the biomarker here.",
    },
}


__all__ = ["FIELD_META", "GROUP_INSTRUCTIONS"]
