"""Extraction metadata for liver cancer (Layer 2 of the three-layer schema).

Layer 1 (shape & enums): :mod:`schemas.pydantic.liver`.
Layer 3 (surface-form aliases): :file:`schemas/aliases/liver.toml` (optional).

EDIT THIS FILE FOR:
  - per-field ``desc`` strings (LM-facing explanations of what to extract).
  - ``GROUP_INSTRUCTIONS`` (per-decomposition-group framing).

DO NOT EDIT THIS FILE FOR:
  - surface-form aliases / synonyms / clone names — those live in
    ``schemas/aliases/liver.toml`` and are merged into ``FIELD_META``
    at registry-build time. Any ``value_hints`` key added here will be
    discarded with a ``UserWarning`` by ``_build_organ_meta`` in
    :mod:`schemas.extraction`.
"""
from __future__ import annotations

from ..pydantic._factory_helpers import DEFAULT_GROUP_INSTRUCTION
from . import FieldMeta

GROUP_INSTRUCTIONS: dict[str, str] = {
    "nonnested":         "you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "extent":            "You need to determine whether the tumor have extended out of liver. If so, extract list of tumor extension to one or more of the specified items below from the given hepatocellular carcinoma excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "vascular_invasion": "You need to determine whether the tumor have vascular invasion. If so, extract list of vascular invasion to one or more of the specified items below from the given hepatocellular carcinoma excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "staging":           "you need to extract the value of the specified items below from the given liver cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "margins":           "you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "lymph_nodes":       "you need to extract the value of the specified items below from the given hepatocellular carcinoma excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
}


FIELD_META: dict[str, FieldMeta] = {
    # --- nonnested ---
    "procedure":      {"group": "nonnested", "desc": "identify which surgery procedure was used. e.g. partial hepatectomy"},
    "tumor_site":     {"group": "nonnested", "desc": "identify the site of the tumor. e.g. right lobe"},
    "histology":      {"group": "nonnested", "desc": "identify the histological type of the cancer. e.g. invasive carcinoma of no special type"},
    "grade":          {"group": "nonnested", "desc": "identify the grade of the cancer, well->1, moderate->2, poor->3, undifferentiated->4"},
    "tumor_size":     {"group": "nonnested", "desc": "identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor"},
    "tumor_focality": {"group": "nonnested", "desc": "identify whether the tumor is unifocal or multifocal"},
    "perineural_invasion": {"group": "nonnested", "desc": "check whether or not perineural invasion is present"},
    "distant_metastasis":  {"group": "nonnested", "desc": "check whether or not distant metastasis is present"},
    "treatment_effect": {
        "group": "nonnested",
        "desc": 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None',
    },

    # --- extent ---
    "tumor_extent": {
        "group": "extent",
        "desc": 'return all of the possible tumor extension. example: ["hepatic_vein", "gallbladder"]. If not present, just output None, do not overdiagnosis',
    },

    # --- vascular_invasion ---
    "vascular_invasion": {
        "group": "vascular_invasion",
        "desc": 'return all of the possible vascular invasion. example: ["large_hepatic_vein", "small_vessel"]. If not present, just output None, do not overdiagnosis',
    },

    # --- staging ---
    "tnm_descriptor": {
        "group": "staging",
        "desc": 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.',
    },
    "pt_category":  {"group": "staging", "desc": "identify the pt category of the tumor"},
    "pn_category":  {"group": "staging", "desc": "identify the pn category of the tumor"},
    "pm_category": {
        "group": "staging",
        "desc": "identify the pm category of the tumor. if you see cM0 or cM1, etc., code as mx, since pathological M category is not available",
    },
    "overall_stage": {"group": "staging", "desc": "identify the overall stage of the tumor"},
    "ajcc_version":  {"group": "staging", "desc": "identify the ajcc version of the pathological staging"},

    # --- margins ---
    "margins": {
        "group": "margins",
        "desc": 'return all of the possible involved margins and its distance from cancer. example:[{"margin_category": "proximal_duodenal", "margin_involved": true, "distance": null}, {"margin_category": "anterior_outmost", "margin_involved": false, "distance": 10}, {"margin_category": "radial", "margin_involved": false, "distance": null}]. If not present, just output null for every margin',
    },
    "margins.margin_category": {
        "desc": "acceptable value for surgical margins in liver cancer. If not included in these standard margins, should be classified as others.",
    },
    "margins.distance": {
        "desc": "If margin is involved, return 0. If margin is uninvolved/free, try your best to find the distance at both microscopic and macroscopic(gross) description, and specify the distance from tumor to margin in mm, rounded to integer. If the margin is uninvolved/free and, after your best effort, the distance is still not specified, return null",
    },

    # --- lymph_nodes (no category, no side) ---
    "regional_lymph_node": {
        "group": "lymph_nodes",
        "desc": 'return all of the involved regional lymph node. example:[{"involved": 2, "examined": 5, "station_name": "station 1"}, {"involved": 0, "examined": 3, "station_name": "station 2"}, ...]. If not present, just output null for every lymph node',
    },
    "regional_lymph_node.station_name": {
        "desc": "specify the name of the lymph node station here.",
    },
    "extranodal_extension": {
        "group": "lymph_nodes",
        "desc": "check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    },
    "maximal_ln_size": {
        "group": "lymph_nodes",
        "desc": "check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    },
}


__all__ = ["FIELD_META", "GROUP_INSTRUCTIONS"]
