"""Extraction metadata for lung cancer (Layer 2 of the three-layer schema).

Layer 1 (shape & enums): :mod:`schemas.pydantic.lung`.
Layer 3 (surface-form aliases): :file:`schemas/aliases/lung.toml`.

EDIT THIS FILE FOR:
  - per-field ``desc`` strings (LM-facing explanations of what to extract).
  - ``GROUP_INSTRUCTIONS`` (per-decomposition-group framing).

DO NOT EDIT THIS FILE FOR:
  - surface-form aliases / synonyms / clone names — those live in
    ``schemas/aliases/lung.toml`` and are merged into ``FIELD_META``
    at registry-build time. Any ``value_hints`` key added here will be
    discarded with a ``UserWarning`` by ``_build_organ_meta`` in
    :mod:`schemas.extraction`.
"""
from __future__ import annotations

from ..pydantic._factory_helpers import DEFAULT_GROUP_INSTRUCTION
from . import FieldMeta

GROUP_INSTRUCTIONS: dict[str, str] = {
    "nonnested":   "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "staging":     "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "margins":     "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "lymph_nodes": "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "biomarkers":  "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "othernested": "you need to extracting the value of the specified items below from the given pathological cancer report" + " " + DEFAULT_GROUP_INSTRUCTION,
}


FIELD_META: dict[str, FieldMeta] = {
    # --- nonnested ---
    "procedure":            {"group": "nonnested", "desc": "identify which surgery procedure was used. e.g. polypectomy"},
    "surgical_technique":   {"group": "nonnested", "desc": "identify how the surgery was taken. e.g. thoracoscopic"},
    "sideness":             {"group": "nonnested", "desc": "identify which side the tumor is located. e.g. right"},
    "cancer_primary_site":  {"group": "nonnested", "desc": "identify the primary site of cancer. e.g. upper_lobe"},
    "tumor_focality":       {"group": "nonnested", "desc": "identify whether the tumor is single focus or multiple foci; this is important for t and m category"},
    "histology":            {"group": "nonnested", "desc": "identify the histological type of the cancer. e.g. adenocarcinoma"},
    "grade":                {"group": "nonnested", "desc": "identify the grade of the cancer, well->1, moderate->2, poor->3, undiff->4"},
    "lymphovascular_invasion":               {"group": "nonnested", "desc": "check whether or not lymphovascular invasion is present"},
    "perineural_invasion":                   {"group": "nonnested", "desc": "check whether or not perineural invasion is present"},
    "spread_through_air_spaces_stas":        {"group": "nonnested", "desc": "check whether or not spread through air spaces (STAS) is present"},
    "visceral_pleural_invasion":             {"group": "nonnested", "desc": "check whether or not visceral pleural invasion is present"},
    "direct_invasion_of_adjacent_structures":{"group": "nonnested", "desc": "check whether or not direct invasion of adjacent structures is present"},
    "distant_metastasis":                    {"group": "nonnested", "desc": "check whether or not distant metastasis is present"},
    "treatment_effect": {
        "group": "nonnested",
        "desc": 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None',
    },

    # --- staging ---
    "tnm_descriptor": {
        "group": "staging",
        "desc": 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.',
    },
    "pt_category":   {"group": "staging", "desc": "identify the pt category of the tumor"},
    "pn_category":   {"group": "staging", "desc": "identify the pn category of the tumor"},
    "pm_category": {
        "group": "staging",
        "desc": "identify the pm category of the tumor. if you see cM0 or cM1, etc., code as mx, since pathological M category is not available",
    },
    "stage_group":   {"group": "staging", "desc": "identify the stage group of the tumor"},
    "ajcc_version":  {"group": "staging", "desc": "identify the ajcc version of the pathological staging"},

    # --- margins ---
    "margins": {
        "group": "margins",
        "desc": 'return all of the possible involved margins and its distance from cancer. example:[{"margin_category": "bronchial", "margin_involved": true, "distance": 5}, {"margin_category": "vascular", "margin_involved": false, "distance": null}, {"margin_category": "parenchymal", "margin_involved": false, "distance": null}]. If not present, just output null for every margin',
    },
    "margins.margin_category": {
        "desc": "acceptable value for surgical margins in lung cancer. If not included in these standard margins, should be classified as others.",
    },
    "margins.distance": {
        "desc": "If margin is involved, return 0. If margin is uninvolved/free, try your best to find the distance at both microscopic and macroscopic(gross) description, and specify the distance from tumor to margin in mm, rounded to integer. If the margin is uninvolved/free and, after your best effort, the distance is still not specified, return null",
    },

    # --- lymph_nodes ---
    "regional_lymph_node": {
        "group": "lymph_nodes",
        "desc": 'return all of the involved regional lymph node. example:[{"lymph_node_side": "right", "lymph_node_category": "4", "involved": 2, "examined": 5}, {"lymph_node_side": "left", "lymph_node_category": "7", "involved": 0, "examined": 3}]. If not present, just output null for every lymph node',
    },
    "regional_lymph_node.lymph_node_side": {
        "desc": "acceptable value for lymph node side in lung cancer. If not included in these standard sides, should be classified as None.",
    },
    "regional_lymph_node.lymph_node_category": {
        "desc": "acceptable value for lymph node categories (i.e. stations or groups) in lung cancer. If not included in these standard lymph node 'stations'/'groups' should be classified as others.",
    },
    "regional_lymph_node.station_name": {
        "desc": "specify the name of the lymph node station/group here.",
    },
    "extranodal_extension": {
        "group": "lymph_nodes",
        "desc": "check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    },
    "maximal_ln_size": {
        "group": "lymph_nodes",
        "desc": "check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    },

    # --- biomarkers ---
    "biomarkers": {
        "group": "biomarkers",
        "desc": 'return all of the examined biomarkers using immunohistochemistry techniques,like alk, ros1, pd-l1. in JSON format. example:[{"biomarker_category": "ALK", "expression": true, "percentage": 70}, {"biomarker_category": "PDL1", "expression": false, "percentage": 0}]. If not present, just output None for every biomarker',
    },
    "biomarkers.biomarker_category": {
        "desc": "acceptable value for biomarker categories in lung cancer. If not included in these standard categories, should be classified as others.",
    },
    "biomarkers.percentage": {
        "desc": "the percentage of tumor cells showing positive expression of the biomarker, rounded to integer. if not specified, return None",
    },
    "biomarkers.biomarker_name": {
        "desc": "specify the name of the biomarker here.",
    },

    # --- othernested ---
    "histological_patterns": {
        "group": "othernested",
        "desc": "if the histology is invasive non-mucinous adenocarcinoma, please identify all of the histological patterns and its percentage. if not, return None",
    },
    "histological_patterns.pattern_name": {
        "desc": "histological pattern of invasive non-mucinous adenocarcinoma",
    },
    "histological_patterns.pattern_percentage": {
        "desc": "percentage of the histological pattern",
    },
}


__all__ = ["FIELD_META", "GROUP_INSTRUCTIONS"]
