"""Extraction metadata for prostate cancer (Layer 2 of the three-layer schema).

Layer 1 (shape & enums): :mod:`schemas.pydantic.prostate`.
Layer 3 (surface-form aliases): :file:`schemas/aliases/prostate.toml` (optional).

EDIT THIS FILE FOR:
  - per-field ``desc`` strings (LM-facing explanations of what to extract).
  - ``GROUP_INSTRUCTIONS`` (per-decomposition-group framing).

DO NOT EDIT THIS FILE FOR:
  - surface-form aliases / synonyms / clone names — those live in
    ``schemas/aliases/prostate.toml`` and are merged into ``FIELD_META``
    at registry-build time. Any ``value_hints`` key added here will be
    discarded with a ``UserWarning`` by ``_build_organ_meta`` in
    :mod:`schemas.extraction`.
"""
from __future__ import annotations

from ..pydantic._factory_helpers import DEFAULT_GROUP_INSTRUCTION
from . import FieldMeta

GROUP_INSTRUCTIONS: dict[str, str] = {
    "nonnested":   "you need to extract the value of the specified items below from the given prostate cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "staging":     "you need to extract the value of the specified items below from the given prostate cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "margins":     "you need to extract the value of the specified items below from the given prostate cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
    "lymph_nodes": "you need to extract the value of the specified items below from the given prostate cancer excision report" + " " + DEFAULT_GROUP_INSTRUCTION,
}


FIELD_META: dict[str, FieldMeta] = {
    # --- nonnested ---
    "procedure":          {"group": "nonnested", "desc": "identify which surgery procedure was used. e.g. radical prostatectomy"},
    "surgical_technique": {"group": "nonnested", "desc": "identify how the surgery was taken. e.g. robotic"},
    "prostate_weight":    {"group": "nonnested", "desc": "identify the weight of the prostate in grams. e.g. 50"},
    "prostate_size":      {"group": "nonnested", "desc": "identify the size of the prostate in mm, largest dimension. e.g. 45 means 45mm"},
    "histology":          {"group": "nonnested", "desc": "identify the histological type of the cancer. e.g. acinar adenocarcinoma"},
    "grade":              {"group": "nonnested", "desc": "identify the gleason group of the cancer. e.g. group_2_3_4 means gleason score 7 (3+4)"},
    "gleason_4_percentage": {"group": "nonnested", "desc": "identify the percentage of gleason pattern 4. e.g. 20 means 20%"},
    "gleason_5_percentage": {"group": "nonnested", "desc": "identify the percentage of gleason pattern 5. e.g. 0 means 0%"},
    "intraductal_carcinoma_presence": {"group": "nonnested", "desc": "check whether or not intraductal carcinoma is present"},
    "cribriform_pattern_presence":    {"group": "nonnested", "desc": "check whether or not cribriform pattern is present. only in gleason score 7 or 8"},
    "tumor_percentage":   {"group": "nonnested", "desc": "identify the percentage of tumor in the prostate in both lobes. e.g. 30 means 30%"},
    "tumor_size":         {"group": "nonnested", "desc": "identify the size of the tumor in mm, largest dimension. e.g. 15 means 15mm"},
    "extraprostatic_extension": {"group": "nonnested", "desc": "check whether or not extraprostatic extension is present"},
    "seminal_vesicle_invasion": {"group": "nonnested", "desc": "check whether or not seminal vesicle invasion is present"},
    "bladder_invasion":         {"group": "nonnested", "desc": "check whether or not bladder invasion is present"},
    "lymphovascular_invasion":  {"group": "nonnested", "desc": "check whether or not lymphovascular invasion is present"},
    "perineural_invasion":      {"group": "nonnested", "desc": "check whether or not perineural invasion is present"},
    "distant_metastasis":       {"group": "nonnested", "desc": "check whether or not distant metastasis is present"},
    "treatment_effect": {
        "group": "nonnested",
        "desc": 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None',
    },

    # --- staging ---
    "tnm_descriptor": {
        "group": "staging",
        "desc": 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.',
    },
    "pt_category":  {"group": "staging", "desc": "identify the pt category of the tumor"},
    "pn_category":  {"group": "staging", "desc": "identify the pn category of the tumor"},
    "pm_category": {
        "group": "staging",
        "desc": "identify the pm category of the tumor. if you see cM0 or cM1, etc., code as mx, since pathological M category is not available",
    },
    "stage_group":  {"group": "staging", "desc": "identify the stage group of the tumor"},
    "ajcc_version": {"group": "staging", "desc": "identify the ajcc version of the pathological staging"},

    # --- margins (non-standard inline shape) ---
    "margin_positivity":    {"group": "margins", "desc": "check whether or not any margin is positive"},
    "involved_margin_list": {"group": "margins", "desc": "list of involved margins"},
    "margin_length": {
        "group": "margins",
        "desc": "if margin is positive, check whether the length of positive margin is limited (<3mm) or non-limited (>=3mm)",
    },

    # --- lymph_nodes ---
    "regional_lymph_node": {
        "group": "lymph_nodes",
        "desc": 'return all of the involved regional lymph node. example:[{"lymph_node_side": "right, "lymph_node_category": "internal_iliac", "involved": 2, "examined": 5}, ...]. If not present, just output null for every lymph node',
    },
    "regional_lymph_node.lymph_node_side": {
        "desc": "acceptable value for lymph node side in prostate cancer. If not included in these standard sides, should be classified as None.",
    },
    "regional_lymph_node.lymph_node_category": {
        "desc": "acceptable value for lymph node categories (i.e. stations) in prostate cancer. If not included in these standard lymph node 'station' number, should be classified as others.",
    },
    "regional_lymph_node.station_name": {
        "desc": "specify the name of the lymph node group/station here.",
    },
    "extranodal_extension": {
        "group": "lymph_nodes",
        "desc": "check whether or not extranodal extension is present; if no lymph node metastasis, should be None",
    },
    "maximal_ln_size": {
        "group": "lymph_nodes",
        "desc": "check the maximal size of node metastatic tumor in mm, rounded to integer; if no lymph node metastasis, should be None",
    },
}


__all__ = ["FIELD_META", "GROUP_INSTRUCTIONS"]
