"""Build ``dspy.Signature`` classes dynamically from Pydantic schemas.

The factory introspects a case-model's :func:`GroupedField`-tagged fields,
groups them by tag, and emits one ``dspy.Signature`` per group (the
``"per_group"`` decomposition mode), or merges all groups into one
monolithic signature. ``"auto"`` decomposition consults the live LM's
``supports_response_schema`` capability + field/group counts.

The runtime construction API ``dspy.Signature(fields_dict, instructions=...)``
and ``make_signature(fields_dict, ..., custom_types=...)`` are stable in
DSPy 3.2.x. ``custom_types`` is required when the schema references nested
``BaseModel`` types (e.g. ``list[BreastMargin]``) — without it, dspy can't
resolve the symbol when serialising the signature for the LM.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Literal

import dspy
from pydantic import BaseModel

from ..schemas.pydantic._factory_helpers import (
    DEFAULT_GROUP_INSTRUCTION,
    field_desc,
    field_group,
    group_instructions,
    group_order,
    iter_custom_types,
    iter_fields_by_group,
)

logger = logging.getLogger(__name__)

# These mirror the legacy `models/<organ>.py` extractor signatures so the
# v2 pipeline can pass through the same inputs untouched.
DEFAULT_INPUT_FIELDS: dict[str, tuple[type, str]] = {
    "report": (
        list,
        "this is a pathological report, separated into paragraphs.",
    ),
    "report_jsonized": (
        dict,
        "this is a roughly structured json summary of the pathological "
        "report, which is generated by another model. May be empty when "
        "ReportJsonize is disabled — extract directly from `report` in that case.",
    ),
}


# Profile names treated as "small" for `auto` decomposition. Anything not
# explicitly small or large falls through to the field/group-count heuristic.
_SMALL_MODEL_PROFILES: frozenset[str] = frozenset({
    "small",
    "ollama_chat/gemma3:4b",
    "ollama_chat/gemma3:1b",
    "ollama_chat/medgemma:4b",
    "ollama_chat/gemma4:e2b",
})

_LARGE_MODEL_PROFILES: frozenset[str] = frozenset({
    "large",
    "openai/gpt-5.4-mini",
})


@dataclass(frozen=True)
class ExtractionStep:
    """One LM call produced by the factory for an organ's extraction.

    ``output_field_names`` is the tuple of *output* field names this step
    is responsible for — useful for parity tests and for emitting per-step
    manifests in the new wrappers.
    """

    name: str
    signature: type[dspy.Signature]
    output_field_names: tuple[str, ...]
    group: str  # source group tag; "<monolithic>" when not decomposed.


def build_signature(
    name: str,
    instructions: str,
    output_fields: dict[str, tuple[Any, str]],
    *,
    input_fields: dict[str, tuple[Any, str]] | None = None,
    custom_types: dict[str, type] | None = None,
) -> type[dspy.Signature]:
    """Build a dspy.Signature with the given inputs and outputs.

    ``output_fields`` is a dict of ``{field_name: (annotation, description)}``;
    same shape for ``input_fields``. ``custom_types`` is forwarded to dspy's
    ``make_signature`` so nested ``BaseModel`` references resolve.

    The Signature class is named ``name`` (cosmetic — affects ``repr`` and
    error messages, not behavior).
    """
    fields_dict: dict[str, tuple[Any, Any]] = {}
    for fname, (ann, desc) in (input_fields or {}).items():
        fields_dict[fname] = (ann, dspy.InputField(desc=desc))
    for fname, (ann, desc) in output_fields.items():
        fields_dict[fname] = (ann, dspy.OutputField(desc=desc))

    # Use make_signature so we can pass custom_types. It's the public-facing
    # constructor; dspy.Signature(dict, instructions=...) routes through the
    # same path but doesn't accept custom_types.
    from dspy.signatures.signature import make_signature

    sig = make_signature(
        fields_dict,
        instructions=instructions,
        signature_name=name,
        custom_types=dict(custom_types or {}),
    )
    return sig


def _choose_decomposition(
    schema: type[BaseModel],
    model_profile: str | None,
) -> Literal["per_group", "monolithic"]:
    """Pick a decomposition mode based on schema shape and live LM capabilities.

    Heuristic (walked in order):
    1. ``model_profile`` explicitly tagged "small" / known small Ollama → per_group.
    2. ``model_profile`` "large" or hosted-frontier AND the configured LM advertises
       ``supports_response_schema`` → monolithic.
    3. Otherwise: per_group if >25 fields or >4 groups, else monolithic.
    """
    if model_profile in _SMALL_MODEL_PROFILES:
        return "per_group"
    if model_profile in _LARGE_MODEL_PROFILES:
        try:
            lm = dspy.settings.lm
            if lm is not None and getattr(lm, "supports_response_schema", False):
                return "monolithic"
        except Exception as e:  # pragma: no cover - defensive
            logger.debug("could not consult dspy.settings.lm: %s", e)

    n_fields = len(schema.model_fields)
    n_groups = len({field_group(fi) for fi in schema.model_fields.values()})
    if n_fields > 25 or n_groups > 4:
        return "per_group"
    return "monolithic"


def build_extraction_signatures(
    schema: type[BaseModel],
    *,
    decomposition: Literal["per_group", "monolithic", "auto"] = "auto",
    model_profile: str | None = None,
) -> list[ExtractionStep]:
    """Build one or more ``ExtractionStep`` records for an organ schema.

    Parameters
    ----------
    schema
        A Pydantic case-model (e.g. ``BreastCancerCase``) whose fields are
        tagged with :func:`GroupedField` and whose
        ``_GROUP_INSTRUCTIONS: ClassVar[dict]`` carries per-group LM
        instructions.
    decomposition
        ``"per_group"``: one signature per group tag (small focused schemas).
        ``"monolithic"``: one signature with all fields (one LM call).
        ``"auto"``: chooses based on ``model_profile`` and the live LM's
        ``supports_response_schema`` flag.
    model_profile
        Hint for ``"auto"`` mode. Pass the dspy/litellm model id (e.g.
        ``"ollama_chat/gpt-oss:20b"``) or the synthetic ``"small"``/``"large"``
        sentinel.
    """
    chosen: Literal["per_group", "monolithic"]
    if decomposition == "auto":
        chosen = _choose_decomposition(schema, model_profile)
    else:
        chosen = decomposition

    custom_types = iter_custom_types(schema)
    schema_doc = (schema.__doc__ or schema.__name__).strip()
    grouped = iter_fields_by_group(schema)
    instr_map = group_instructions(schema)
    order = group_order(schema)
    base = schema.__name__.replace("Case", "")  # e.g. "BreastCancer"

    if chosen == "monolithic":
        out_fields: dict[str, tuple[Any, str]] = {}
        for g in order:
            for name, ann, fi in grouped.get(g, []):
                out_fields[name] = (ann, field_desc(fi))
        # Fields under "<ungrouped>" still need to land somewhere.
        for name, ann, fi in grouped.get("<ungrouped>", []):
            out_fields.setdefault(name, (ann, field_desc(fi)))
        sig = build_signature(
            name=f"{base}__monolithic",
            instructions=schema_doc,
            output_fields=out_fields,
            input_fields=DEFAULT_INPUT_FIELDS,
            custom_types=custom_types,
        )
        return [
            ExtractionStep(
                name=f"{base}__monolithic",
                signature=sig,
                output_field_names=tuple(out_fields),
                group="<monolithic>",
            )
        ]

    # decomposition == "per_group"
    steps: list[ExtractionStep] = []
    seen_field_names: set[str] = set()  # first-wins, mirrors legacy semantics.
    for g in order:
        fields = grouped.get(g, [])
        if not fields:
            continue
        out_fields: dict[str, tuple[Any, str]] = {}
        for name, ann, fi in fields:
            if name in seen_field_names:
                continue
            out_fields[name] = (ann, field_desc(fi))
            seen_field_names.add(name)
        if not out_fields:
            continue
        per_group_instr = instr_map.get(g) or DEFAULT_GROUP_INSTRUCTION
        instructions = f"{schema_doc}\n\n{per_group_instr}".strip()
        sig = build_signature(
            name=f"{base}__{g}",
            instructions=instructions,
            output_fields=out_fields,
            input_fields=DEFAULT_INPUT_FIELDS,
            custom_types=custom_types,
        )
        steps.append(
            ExtractionStep(
                name=f"{base}__{g}",
                signature=sig,
                output_field_names=tuple(out_fields),
                group=g,
            )
        )
    return steps


# --- Router (is_cancer) ---------------------------------------------------

ROUTER_INSTRUCTIONS = (
    "You are a cancer registrar, you need to identify whether or not this "
    "report belongs to PRIMARY cancer excision eligible for cancer registry, "
    "and if so, which organ the cancer belongs to. If no viable tumor is "
    "present after excision, you should not register this case. If only "
    "carcinoma in situ or high-grade dysplasia, you should not register this "
    "case."
)

_ROUTER_REPORT_DESC = (
    "this is a pathologic report, separated into paragraphs. you should "
    "determine whether or not this report belongs to cancer excision "
    "eligible for cancer registry"
)


def _registry_keys(registry: dict[str, type[BaseModel]] | None) -> list[str]:
    if registry is not None:
        return sorted(registry.keys())
    # Lazy import to avoid a circular dependency at module load time.
    from ..schemas import CASE_MODELS  # type: ignore[attr-defined]
    return sorted(CASE_MODELS.keys())


def build_router_signature(
    registry: dict[str, type[BaseModel]] | None = None,
) -> type[dspy.Signature]:
    """Build the registry-driven ``is_cancer`` router.

    The ``cancer_category`` Literal is auto-derived from
    ``sorted(registry.keys()) + ["others"]``. Adding a new organ to the
    registry updates the router on the next pipeline construction — no
    edits to this file or the legacy ``is_cancer`` signature.
    """
    keys = _registry_keys(registry) + ["others"]
    cancer_category_t = Literal[tuple(keys)] | None  # type: ignore[valid-type]
    return build_signature(
        name="IsCancer",
        instructions=ROUTER_INSTRUCTIONS,
        input_fields={"report": (list, _ROUTER_REPORT_DESC)},
        output_fields={
            "cancer_excision_report": (
                bool,
                "identify whether or not this report belongs to PRIMARY cancer "
                "excision eligible for registry for cancer excision. If no viable "
                "tumor is present after excision, you should not register this "
                "case. If only carcinoma in situ or high-grade dysplasia, you "
                "should not register this case.",
            ),
            "cancer_category": (
                cancer_category_t,
                "identify which organ the primary cancer arises from. If it IS a "
                "cancer excision report but the primary site is not in the "
                "registered organs, classify as 'others'.",
            ),
            "cancer_category_others_description": (
                str | None,
                "if cancer_excision_report AND cancer_category is 'others', "
                "specify the organ here. Otherwise return null.",
            ),
        },
    )


# --- Jsonize (ReportJsonize) ----------------------------------------------

JSONIZE_INSTRUCTIONS = (
    "You are cancer registrar, and you are assigned a task to manually "
    "convert the raw pathology report into a roughly structured json format. "
    "Keep original wording as much as possible. Try to follow the order of "
    "cancer checklists."
)

_JSONIZE_REPORT_DESC = (
    "this is a raw pathological report, separated into paragraphs. You need "
    "to convert it into a roughly structured json format, keeping original "
    "wording as much as possible."
)


def build_jsonize_signature(
    registry: dict[str, type[BaseModel]] | None = None,
) -> type[dspy.Signature]:
    """Build the optional ``ReportJsonize`` preprocessing signature.

    NOTE: the ``cancer_category`` Literal here intentionally does NOT
    include ``"others"`` — preserving the asymmetry from the legacy
    ``ReportJsonize`` signature in ``models/common.py``. If you want to
    fix that, do it explicitly here, not as a side effect.
    """
    keys = _registry_keys(registry)  # NO "others"
    cancer_category_t = Literal[tuple(keys)] | None  # type: ignore[valid-type]
    return build_signature(
        name="ReportJsonize",
        instructions=JSONIZE_INSTRUCTIONS,
        input_fields={
            "report": (list, _JSONIZE_REPORT_DESC),
            "cancer_category": (
                cancer_category_t,
                "which part the cancer belongs to. You need to convert it into a "
                "roughly structured json format, keeping original wording as much "
                "as possible.",
            ),
        },
        output_fields={
            "output": (
                dict,
                "Roughly-structured JSON dump of the raw pathology report. "
                "Keep original wording as much as possible. Try to follow the "
                "order of cancer checklists.",
            ),
        },
    )


__all__ = [
    "ExtractionStep",
    "DEFAULT_INPUT_FIELDS",
    "ROUTER_INSTRUCTIONS",
    "JSONIZE_INSTRUCTIONS",
    "build_signature",
    "build_extraction_signatures",
    "build_router_signature",
    "build_jsonize_signature",
]
