# -*- coding: utf-8 -*-
"""
models/bladder.py
This script sets up a series of data extraction models using the dspy library for pathology reports, specifically focusing on bladder cancer. It includes model loading, signature definitions for various cancer types, and functions to convert model predictions into structured JSON formats.

author: Hong-Kai (Walther) Chen, Po-Yen Tzeng and Kai-Po Chang @ Med NLP Lab, China Medical University
date: 2025-10-06
"""
__version__ = "0.1.0"
__date__ = "2025-10-06"
__author__ = ["Hong-Kai (Walther) Chen", "Po-Yen Tzeng", "Kai-Po Chang"]
__copyright__ = "Copyright 2025, Med NLP Lab, China Medical University"
__license__ = "MIT"
__ajcc_version__ = 8
__cap_version__ = "4.2.0.0"

import dspy
from typing import Literal
from pydantic import BaseModel, Field

class BladderMargin (BaseModel):
    margin_category: Literal["right_ureteral", "left_ureteral", "urethral", "outmost", "others"]|None = Field(None, description="acceptable value for surgical margins in bladder cancer. If not included in these standard margins, should be classified as others.")
    margin_involved: bool
    distance: int|None = Field(None, description="the distance of the margin from the tumor in mm, rounded to integer. if margin is involved, return 0. if not specified, return null")
    description: str|None

class BladderLN (BaseModel):
    lymph_node_side: Literal["right", "left", "midline", "side_not_specified"]|None = Field(None, description="acceptable value for lymph node side in breast cancer. If not included in these standard sides, should be classified as side_not_specified.")
    lymph_node_category: Literal["sentinel", "nonsentinel", "others"]|None = Field(None, description="acceptable value for lymph node categories (i.e. stations) in breast cancer. If not included in these standard lymph node 'station' number, should be classified as others.")
    involved: int
    examined: int
    station_name: str|None = Field(None, description="specify the name of the lymph node station here.")

class BladderCancerNonnested(dspy.Signature):
    """you need to extract the value of the specified items below from the given bladder cancer excision report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS."""
    report: list = dspy.InputField(desc = 'this is a pathological report for bladder cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    procedure: Literal['partial_cystectomy', 'radical_cystectomy', 'radical_cystoprostatectomy', 'others']|None = dspy.OutputField(desc = 'identify which surgery procedure was used. e.g. partial cystectomy')   
    tumor_site: Literal["trigone", "dome", "anterior_wall", "posterior_wall", "right_lateral_wall", "left_lateral_wall", "bladder_neck", "ureteral_orifice", "others"]|None = dspy.OutputField(desc = 'identify the primary site of cancer. e.g. trigone')
    histology: Literal["noninvasive_papillary", "invasive_urothelial_carcinoma", "squamous_cell_carcinoma", "adenocarcinoma"]|None = dspy.OutputField(desc = 'identify the histological type of the cancer. e.g. invasive urothelial carcinoma')
    tumor_size: int|None = dspy.OutputField(desc = 'identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor')
    lymphovascular_invasion: bool|None = dspy.OutputField(desc = 'check whether or not lymphovascular invasion is present')
    perineural_invasion: bool|None = dspy.OutputField(desc = 'check whether or not perineural invasion is present')
    distant_metastasis: bool|None = dspy.OutputField(desc = 'check whether or not distant metastasis is present')
    treatment_effect: str|None = dspy.OutputField(desc = 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None')

class dcis(dspy.Signature):
    """
    You need to extract data about ductal carcinoma in situ below from the given pathological cancer report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS.
    """

    report: str = dspy.InputField(desc = 'this is a pathological report for breast cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    dcis_present: bool|None = dspy.OutputField(desc = 'check whether or not ductal carcinoma in situ is present')
    dcis_size: int|None = dspy.OutputField(desc = 'if ductal carcinoma in situ is present, identify the size of the largest DCIS in mm, rounded')
    dcis_comedo_necrosis: bool|None = dspy.OutputField(desc = 'if ductal carcinoma in situ is present, check whether or not comedo necrosis is present')
    dcis_grade: Literal[1, 2, 3]|None = dspy.OutputField(desc = 'if ductal carcinoma in situ is present, identify the grade of DCIS, low grade (grade 1), intermediate grade (grade 2), high grade (grade 3)')

class BreastCancerStaging(dspy.Signature):
    """you need to extract the value of the specified items below from the given breast cancer excision report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS."""

    report: str = dspy.InputField(desc = 'this is a pathological report for breast cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    tnm_descriptor: Literal['y', 'r', 'm']|None = dspy.OutputField(desc = 'identify the tnm descriptor of the tumor. e.g., "y" (post-therapy), "r", etc.')
    pt_category: Literal["tx", "tis", "t1mi", "t1a", "t1b", "t1c", "t2", "t3", "t4a", "t4b", "t4c"]|None = dspy.OutputField(desc = 'identify the pt category of the tumor')
    pn_category: Literal["nx", "n0", "n1a", "n1b", "n1c", "n2a", "n2b", "n3a", "n3b", "n3c"]|None = dspy.OutputField(desc = 'identify the pn category of the tumor')
    pm_category: Literal["mx", "m0", "m1a", "m1b", "m1c"]|None = dspy.OutputField(desc = 'identify the pm category of the tumor. if you see cM0 or cM1, etc., please return accordingly')
    pathologic_stage_group: Literal["0", "ia", "ib", "iia", "iib", "iiia", "iiib","iiic", "iv"]|None = dspy.OutputField(desc = 'identify the pathologic stage group of the tumor')
    anatomic_stage_group: Literal["0", "ia", "ib", "iia", "iib", "iiia", "iiib","iiic", "iv"]|None = dspy.OutputField(desc = 'identify the anatomic stage group of the tumor')
    ajcc_version: int|None = dspy.OutputField(desc = 'identify the ajcc version of the pathological staging')

class BreastCancerMargins(dspy.Signature):
    """you need to extract the value of the specified items below from the given breast cancer excision report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS."""

    report: str = dspy.InputField(desc = 'this is a pathological report for breast cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    margins: list[BladderMargin]|None = dspy.OutputField(desc = '''return all of the possible involved margins and its distance from cancer. example:[{"margin_category": "proximal", "margin_involved": true, "distance": 5}, {"margin_category": "distal", "margin_involved": false, "distance": null}, {"margin_category": "radial", "margin_involved": false, "distance": null}]. If not present, just output null for every margin''')

class BreastCancerLN(dspy.Signature):
    """you need to extract the value of the specified items below from the given breast cancer excision report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS."""

    report: str = dspy.InputField(desc = 'this is a pathological report for breast cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    regional_lymph_node: list[BladderLN]|None = dspy.OutputField(desc = '''return all of the involved regional lymph node. example:[{"lymph_node_side": "right", "lymph_node_category": "sentinel", "involved": 2, "examined": 5, "station_name": "station 1"}, {"lymph_node_side": "left", "lymph_node_category": "nonsentinel", "involved": 0, "examined": 3, "station_name": "station 2"}, ...]. If not present, just output null for every lymph node''')
    extranodal_extension: bool|None = dspy.OutputField(desc = 'check whether or not extranodal extension is present')
    maximal_ln_size: int|None = dspy.OutputField(desc =
     'check the maximal size of node metastatic tumor in mm, rounded to integer. if not, return None')

class BreastCancerBiomarkers(dspy.Signature):
    """you need to extract breast cancer biomarkers, which is very important, below from the given pathological cancer report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS. """
    report: str = dspy.InputField(desc = 'this is a pathological report for breast cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    biomarkers: str|None = dspy.OutputField(desc = '''return all of the examined immunoreceptors using immunohistochemistry techniques,like er, pr, her2, ki67, etc. in a list of pydantic structures, 
    example: [{"biomarker_category": "er", "expression": true, "percentage": 90, "score": null, "biomarker_name": "estrogen receptor"}, 
    {"biomarker_category": "pr", "expression": false, "percentage": 0, "score": null, "biomarker_name": "progesterone receptor"}, 
    {"biomarker_category": "her2", "expression": null, "percentage": 0, "score": 2, "biomarker_name": "human epidermal growth factor receptor 2"}, 
    {"biomarker_category": "ki67", "expression": null, "percentage": 30, "score": null, "biomarker_name": "ki67 proliferation index"}]. If not present, just output null for every biomarker''')
