# -*- coding: utf-8 -*-
"""
models/bladder.py
This script sets up a series of data extraction models using the dspy library for pathology reports, specifically focusing on bladder cancer. It includes model loading, signature definitions for various cancer types, and functions to convert model predictions into structured JSON formats.

author: Hong-Kai (Walther) Chen, Po-Yen Tzeng and Kai-Po Chang @ Med NLP Lab, China Medical University
date: 2025-10-06
"""
__version__ = "0.1.0"
__date__ = "2025-10-06"
__author__ = ["Hong-Kai (Walther) Chen", "Po-Yen Tzeng", "Kai-Po Chang"]
__copyright__ = "Copyright 2025, Med NLP Lab, China Medical University"
__license__ = "MIT"
__ajcc_version__ = 8
__cap_version__ = "4.2.0.0"

import dspy
from typing import Literal
from pydantic import BaseModel, Field

class BladderMargin (BaseModel):
    margin_category: Literal["right_ureteral", "left_ureteral", "urethral", "outmost", "others"]|None = Field(None, description="acceptable value for surgical margins in bladder cancer. If not included in these standard margins, should be classified as others.")
    margin_involved: bool
    distance: int|None = Field(None, description="the distance of the margin from the tumor in mm, rounded to integer. if margin is involved, return 0. if not specified, return null")
    description: str|None

class BladderLN (BaseModel):
    lymph_node_side: Literal["right", "left", "midline", "side_not_specified"]|None = Field(None, description="acceptable value for lymph node side in breast cancer. If not included in these standard sides, should be classified as side_not_specified.")
    lymph_node_category: Literal["sentinel", "nonsentinel", "others"]|None = Field(None, description="acceptable value for lymph node categories (i.e. stations) in breast cancer. If not included in these standard lymph node 'station' number, should be classified as others.")
    involved: int
    examined: int
    station_name: str|None = Field(None, description="specify the name of the lymph node station here.")

class BladderCancerNonnested(dspy.Signature):
    """you need to extract the value of the specified items below from the given bladder cancer excision report. DO NOT JUST RETURN NULL. IF SOME ITEM IS NOT PRESENT, RETURN NULL FOR THAT ITEM, BUT TRY YOUR BEST TO FILL IN THE OTHERS."""
    report: list = dspy.InputField(desc = 'this is a pathological report for bladder cancer excision')
    report_jsonized: dict = dspy.InputField(desc = 'this is a roughly structured json summary of the pathological report, which is generated by another model.')
    procedure: Literal['partial_cystectomy', 'radical_cystectomy', 'radical_cystoprostatectomy', 'others']|None = dspy.OutputField(desc = 'identify which surgery procedure was used. e.g. partial cystectomy')   
    tumor_site: Literal["trigone", "dome", "anterior_wall", "posterior_wall", "right_lateral_wall", "left_lateral_wall", "bladder_neck", "ureteral_orifice", "others"]|None = dspy.OutputField(desc = 'identify the primary site of cancer. e.g. trigone')
    histology: Literal["noninvasive_papillary", "invasive_urothelial_carcinoma", "squamous_cell_carcinoma", "adenocarcinoma"]|None = dspy.OutputField(desc = 'identify the histological type of the cancer. e.g. invasive urothelial carcinoma')
    tumor_size: int|None = dspy.OutputField(desc = 'identify the size of the tumor in mm, rounded, if multiple tumors are present, please provide the size of the largest tumor')
    lymphovascular_invasion: bool|None = dspy.OutputField(desc = 'check whether or not lymphovascular invasion is present')
    perineural_invasion: bool|None = dspy.OutputField(desc = 'check whether or not perineural invasion is present')
    distant_metastasis: bool|None = dspy.OutputField(desc = 'check whether or not distant metastasis is present')
    treatment_effect: str|None = dspy.OutputField(desc = 'check the treatment effect of the cancer. If you see "No known presurgical therapy", return None')

